// Autogenerated by EvDSL
package riseevents.ev.repository;
import riseevents.ev.util.LibraryOfDSL;
import java.util.List;
import riseevents.ev.data.NewClass;
import riseevents.ev.exception.NewClassNotFoundException;
import riseevents.ev.exception.RepositoryException;

public interface NewClassRepository {

	public void insert(NewClass newclass) throws RepositoryException;

	public void remove(NewClass newclass) throws NewClassNotFoundException, RepositoryException;

	public NewClass search(int idEntity) throws NewClassNotFoundException, RepositoryException;
	
	public List<NewClass> getNewClassList() throws RepositoryException;

	public void update(NewClass newclass) throws NewClassNotFoundException, RepositoryException;

	public boolean isThere(int idEntity) throws RepositoryException;
	
	public int getNewClassLastId() throws RepositoryException;
	
	public List<NewClass> getNewClassById(int idActivity) throws RepositoryException;

}