// Autogenerated by EvDSL
package riseevents.ev.repository;
import riseevents.ev.util.LibraryOfDSL;
import java.util.List;
import riseevents.ev.data.NewClass;
import riseevents.ev.exception.NewClassNotFoundException;
import riseevents.ev.exception.RepositoryException;

public interface NewClassRepository {

	public void insert(NewClass activityOrganzier) throws RepositoryException;

	public void remove(NewClass activityOrganzier) throws NewClassNotFoundException, RepositoryException;

	public NewClass search(int idEntity) throws NewClassNotFoundException, RepositoryException;
	
	public List<NewClass> getActivitiesOrganizers() throws RepositoryException;

	public void update(NewClass activityOrganzier) throws NewClassNotFoundException, RepositoryException;

	public boolean isThere(NewClass activityOrganzier) throws RepositoryException;
	
	public int getNewClassLastId() throws RepositoryException;
	
	public List<NewClass> getActivitiesById(int idActivity) throws RepositoryException;

}