// Autogenerated by EvDSL
package riseevents.ev.table;
import riseevents.ev.util.LibraryOfDSL;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import riseevents.ev.util.ExceptionMessages;
import riseevents.ev.data.NewOption;

public class NewOptionTableModel extends AbstractTableModel{
	// Nome das Colunas
		
			private static final int COL_NEWOPTIONID = 0;
			private static final int COL_TYPENEWOPTION = 3;
			// Lista de Valores
			private List<NewOption> rows;
			
			public NewOptionTableModel(List<NewOption> values){
				this.rows = values;
			}
			
			public int getRowCount() {
				return rows.size();
			}
			
			//Quantidade de Colunas
			public int getColumnCount() {
				return 0;
			}
			
			//Preenchimento de cada coluna
				public Object getValueAt(int rowIndex, int columnIndex) {
					NewOption newoption = rows.get(rowIndex);
					if (columnIndex == COL_NEWOPTIONID) {
						return newoption.getIdNewOption();
					}
					return null;
				}
				
				@Override
				public String getColumnName(int column) {
					String coluna = "";
					switch (column) {
				case COL_TYPENEWOPTION:
					coluna = "Tipo";
					break;
			
					default:
						throw new IllegalArgumentException(ExceptionMessages.EXC_INVALID_COL);
					}
					return coluna;
				}
				
				//Tipo de valor da colna
				@Override
				public Class<?> getColumnClass(int columnIndex) {
					return null;
				}
				
				//Abaixo metodos de InserÁ„o, remoÁ„o, update e etc;
				public NewOption get(int row) {
					return rows.get(row);
				}

				public void addNewOption(NewOption newoption) {
					rows.add(newoption);
					int ultimoIndice = getRowCount() - 1;
					fireTableRowsInserted(ultimoIndice, ultimoIndice);
				}
				
				public void removeNewOption(int indiceLinha) {
					rows.remove(indiceLinha);
					fireTableRowsDeleted(indiceLinha, indiceLinha);
				}
				
				public void alterarNewOption(int indiceLinha, NewOption newoption) {
					fireTableDataChanged();
				}
				
				//real name listade....
				public void addNewOptionList(List<NewOption> newoptionList) {
					int indice = getRowCount();
					rows.addAll(newoptionList);
					fireTableRowsInserted(indice, indice + newoptionList.size());
				}
				
				public int retornarIndice(NewOption newoption) {
					return rows.indexOf(newoption);
				}
				
				// Remove todos os registros.
				public void limpar() {
					rows.clear();

					// Notifica a mudança.
					fireTableDataChanged();
				}
}