//#if ${AssignmentChairindication} == "T" or ${Assignmentautomatic} == "T"
package riseevents.ev.data;

import java.util.ArrayList;
import java.util.List;



public class Assignment {
	private int idReviwerUser;
	private int idReview;
	private int idReviewSubmission;
	private String date;
	//generated By DSL
	private int newAssigmentField;
	//
	//generated By DSL
	private TypeAssignment typeAssignment;
	public enum TypeAssignment{
			Associado,
			Profissional,
			Estudante
	
	}
	//

	//generated By DSL
	public TypeAssignment getTypeAssignment(){
		return this.typeAssignment;
	}
	public void setTypeAssignment(TypeAssignment new_value){
		this.typeAssignment = new_value;
	}
	//
	
	//generated By DSL
  	public int getNewassigmentfield(){
    	return this.newAssigmentField;
  	}
	public void setNewassigmentfield(int new_value){
    	this.newAssigmentField = new_value;
  	}
	//

	public int getIdReview() {
		return idReview;
	}
	public void setIdReview(int idReview) {
		this.idReview = idReview;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public int getIdReviwerUser() {
		return idReviwerUser;
	}
	public void setIdReviwerUser(int idReviwerUser) {
		this.idReviwerUser = idReviwerUser;
	}
	public int getIdReviewSubmission() {
		return idReviewSubmission;
	}
	public void setIdReviewSubmission(int idReviewSubmission) {
		this.idReviewSubmission = idReviewSubmission;
	}
	
	public String toString(){
		return "Review Id:"+ idReview + "\nReviewer User Id:" + idReviwerUser + "\nReview Submission Id:" + idReviewSubmission + "\nDate:" + date
		//generated By DSL
		+ "Newassigmentfield:" + newAssigmentField
		+ "TypeAssignment:" + typeAssignment 		
	;
	}
	
	//a lista de submissao que a funcao recebe eh uma lista do getSubmissions(todas elas)
//	public List<Submission> automaticoPreferenceIndication(Reviewer reviewer, List<Submission> submissions){
//		List<Submission> submissions2 = new ArrayList<Submission>();
//
//		
//		for(Submission s : submissions){
//			String keyword = s.getKeywords();
//			String knowledgeArea = reviewer.getKnowledgeArea();
//			if(knowledgeArea.equals(keyword)){
//				submissions2.add(s);
//				return submissions2;
//			}
//		}
//		return submissions;
//	}
	
}
//#endif