//#if ${InsertAuthors} == "T"
package riseevents.ev.data;

public class Author {

	private int idAuthor;
	private String name;
	private String filiation;
	private String email;
	//generated By DSL
	private String lattes;
	private int aaaa;
	private String bbbb;
	//
	//generated By DSL
	private TypeAuthor typeAuthor;
	public enum TypeAuthor{
			Associado,
			Profissional,
			Estudante
	
	}
	//

	//generated By DSL
	public TypeAuthor getTypeAuthor(){
		return this.typeAuthor;
	}
	public void setTypeAuthor(TypeAuthor new_value){
		this.typeAuthor = new_value;
	}
	//
	
	//generated By DSL
  	public String getLattes(){
    	return this.lattes;
  	}
	public void setLattes(String new_value){
    	this.lattes = new_value;
  	}
  	public int getAaaa(){
    	return this.aaaa;
  	}
	public void setAaaa(int new_value){
    	this.aaaa = new_value;
  	}
  	public String getBbbb(){
    	return this.bbbb;
  	}
	public void setBbbb(String new_value){
    	this.bbbb = new_value;
  	}
	//

	public int getIdAuthor() {
		return idAuthor;
	}
	public void setIdAuthor(int idAuthor) {
		this.idAuthor = idAuthor;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getFiliation() {
		return filiation;
	}
	public void setFiliation(String filiation) {
		this.filiation = filiation;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}

	public String toString(){
		return "Author Id:"+ idAuthor + "\nName:" + name + "\nFiliation:" + filiation + "\nEmail:" + email
		//generated By DSL
		+ "Lattes:" + lattes
		+ "Aaaa:" + aaaa
		+ "Bbbb:" + bbbb
		+ "TypeAuthor:" + typeAuthor 		
	;
	}
}
//#endif