//#if ${CheckingCopyCertificado} == "T" or ${CheckingCopyAtestado} == "T"
package riseevents.ev.data;

import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;

import javax.swing.JOptionPane;

import com.itextpdf.text.Element;
import com.lowagie.text.Document;
import com.lowagie.text.DocumentException;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;

public class CheckingCopy {

	private int idCheckingCopy;
	private int idUser;
	private int idRegistration;
	private String dateOfIssue;
	//generated By DSL
	private String banana;
	//
	//generated By DSL
	private TypeCheckingCopy typeCheckingCopy;
	private enum TypeCheckingCopy{
			Atestado,
			Certificado
	
	}
	//

	//generated By DSL
	public TypeCheckingCopy getTypeCheckingCopy(){
		return this.typeCheckingCopy;
	}
	public void setTypeCheckingcopy(TypeCheckingCopy new_value){
		this.typeCheckingCopy = new_value;
	}
	//
	
	//generated By DSL
  	public String getBanana(){
    	return this.banana;
  	}
	public void setBanana(String new_value){
    	this.banana = new_value;
  	}
	//

	public int getIdCheckingCopy() {
		return idCheckingCopy;
	}
	public void setIdCheckingCopy(int idCheckingCopy) {
		this.idCheckingCopy = idCheckingCopy;
	}
	public int getIdUser() {
		return idUser;
	}
	public void setIdUser(int idUser) {
		this.idUser = idUser;
	}
	public int getIdRegistration() {
		return idRegistration;
	}
	public void setIdRegistration(int idRegistration) {
		this.idRegistration = idRegistration;
	}
	public String getDateOfIssue() {
		return dateOfIssue;
	}
	public void setDateOfIssue(String dateOfIssue) {
		this.dateOfIssue = dateOfIssue;
	}
	public String toString(){
		return "CheckingCopy Id:"+ idCheckingCopy + "\nRegistration Id:" + idRegistration + "\nUser Id:" + idUser + "\nDate of Issue:" + dateOfIssue
			//generated By DSL
			+ "Banana:" + banana
			+ "TypeCheckingCopy:" + typeCheckingCopy 		
		;
	}
	
	

	private String getTexto(String evento, String periodo, String atividade) {
		 String lista_minicursos = "\n\n";
		 String texto = "";
			//generated By DSL
			if (atividade.equals("MiniCurso")){
				 texto = "Participou de um Mini " + " no(a) " + evento + ", realizado(a) no periodo de " + periodo;
		            texto += lista_minicursos;
			}
			//
			//generated By DSL
			if (atividade.equals("Tutorial")){
				 texto = "Participou de um Tutorial " + " no(a) " + evento + ", realizado(a) no periodo de " + periodo;
		            texto += lista_minicursos;
			}
			//
			//generated By DSL
			if (atividade.equals("Painel")){
				 texto = "Participou de um Painel " + " no(a) " + evento + ", realizado(a) no periodo de " + periodo;
		            texto += lista_minicursos;
			}
			//
			//generated By DSL
			if (atividade.equals("Workshop")){
				 texto = "Participou de um Workshop " + " no(a) " + evento + ", realizado(a) no periodo de " + periodo;
		            texto += lista_minicursos;
			}
			//
		return texto;
	}	 
}
//#endif