// Autogenerated by EvDSL
import riseevents.ev.util.LibraryOfDSL;

class NewClass {
  private int idNewClass;

  private int banana;

  private TypeNewClass typeNewClass;
  public enum TypeNewClass{
      AAAA,
      BBB
  
  }

  public TypeNewClass getTypeNewClass(){
    return this.typeNewClass;
  }
  public void setTypeNewclass(TypeNewClass new_value){
    this.typeNewClass = new_value;
  }
 

  public int getIdNewClass(){
    return this.idNewClass;
  }
  public void setIdNewClass(int new_value){
    this.idNewClass = new_value;
  }
    public int getBanana(){
      return this.banana;
    }
  public void setBanana(int new_value){
      this.banana = new_value;
    }
}