// Autogenerated by EvDSL
package riseevents.ev.data;
import riseevents.ev.util.LibraryOfDSL;

public class Newclass {
  private int idNewclass;

  private int aaaa;
  private String bbbb;

  private TypeNewclass typeNewclass;
  public enum TypeNewclass{
      AAAA,
      BBB
  
  }

  public TypeNewclass getTypeNewclass(){
    return this.typeNewclass;
  }
  public void setTypeNewclass(TypeNewclass new_value){
    this.typeNewclass = new_value;
  }
 

  public int getIdNewclass(){
    return this.idNewclass;
  }
  public void setIdNewclass(int new_value){
    this.idNewclass = new_value;
  }
    public int getAaaa(){
      return this.aaaa;
    }
  public void setAaaa(int new_value){
      this.aaaa = new_value;
    }
    public String getBbbb(){
      return this.bbbb;
    }
  public void setBbbb(String new_value){
      this.bbbb = new_value;
    }
}