//#if ${Reviewer} == "T"
package riseevents.ev.data;

public class Reviewer extends User{

	private String knowledgeArea;
	//generated By DSL
	private TypeReviewer typeReviewer;
	public enum TypeReviewer{
			Associado,
			Profissional,
			Estudante
	
	}
	//

	//generated By DSL
	public TypeReviewer getTypeReviewer(){
		return this.typeReviewer;
	}
	public void setTypeReviewer(TypeReviewer new_value){
		this.typeReviewer = new_value;
	}
	//
	

	public String getKnowledgeArea() {
		return knowledgeArea;
	}

	public void setKnowledgeArea(String knowledgeArea) {
		this.knowledgeArea = knowledgeArea;
	}

	@Override
	public boolean equals(Object obj) { 
		if (obj == this) { 
			return true; 
		} 
		if (obj == null || obj.getClass() != this.getClass()) { 
			return false; 
		} 
		
		Reviewer reviewer = (Reviewer) obj; 
		
		return (this.getIdUser() == ((Reviewer)obj).getIdUser() && 
				   this.getPassword().equals(((Reviewer)obj).getPassword()) && 
				   this.getNameUser().equals(((Reviewer)obj).getNameUser()) &&
				   this.getTypeUser() == ((Reviewer)obj).getTypeUser() &&
				   this.getEmail().equals(((Reviewer)obj).getEmail())&&
				   this.getKnowledgeArea().equals(((Reviewer)obj).getKnowledgeArea()));
	}
	
	public String toString(){
		//return "User Id:"+ getIdUser() + "\nName:" + getNameUser() + "\nType:" + getTypeUser().toString() + "\nEmail:" + getEmail()   + "\nKnowledgeArea:" + knowledgeArea + "\nFiliation:" + getFiliation() ;
		//return "\nKnowledge Area:" + knowledgeArea;
		return super.toString()  + "\nKnowledgeArea:" + knowledgeArea
		+ "Type:" + type 		
	;
	}

}
//#endif