// Autogenerated by EvDSL
import riseevents.ev.util.LibraryOfDSL;
package riseevents.ev.exception;
import riseevents.ev.util.ExceptionMessages;

public class NewClassFoundException extends Exception {

    private int idEntity;

    public NewClassNotFoundException(int idEntity){
        super (ExceptionMessages.EXC_NOT_FOUND);
        this.idEntity = idEntity;
    }

    public int getIdNewClass(){
        return idEntity;
    }

}
//#endif