// Autogenerated by EvDSL
package riseevents.ev.exception;
import riseevents.ev.util.LibraryOfDSL;
import riseevents.ev.util.ExceptionMessages;

public class NewClassNotFoundException extends Exception {
    private int idEntity;

    public NewClassNotFoundException(int idEntity){
        super (ExceptionMessages.EXC_NOT_FOUND);
        this.idEntity = idEntity;
    }

    public int getIdNewClass(){
        return idEntity;
    }

}