// Autogenerated by EvDSL
import riseevents.ev.util.LibraryOfDSL;
package riseevents.ev.exception;
import riseevents.ev.util.ExceptionMessages;

public class NewClassAlreadyInsertedException extends Exception {

	private int idEntity;

	public NewClassAlreadyInsertedException(int idEntity) {
		super(ExceptionMessages.EXC_ALREADY_EXISTS);
		this.idEntity = idEntity;
	}

	public int getIdNewClass() {
		return idEntity;
	}
}
//#endif