// Autogenerated by EvDSL
package riseevents.ev.ui2;
import riseevents.ev.util.LibraryOfDSL;
import java.awt.Color;
import java.awt.EventQueue;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyVetoException;

import javax.swing.ImageIcon;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.WindowConstants;
import javax.swing.border.EmptyBorder;

import riseevents.ev.facade.RiseEventsFacade;

public class RiseEventsMainScreenP extends JFrame {

	private JPanel contentPane;
	
    public static RiseEventsFacade facade; // caso a variabilidade de tela login seja retirada o sistema deve iniciar dessa tela
	
	private static RiseEventsMainScreenP instanceRiseEventsMainScreenP;      
	
	private UserInsertScreenP screenInsertUser;	
	private UserUpdateScreenP screenUpdateUser;	
	private UserSearchScreenP screenSearchUser;	
	private UserRemoveScreenP screenRemoveUser;	
	private UserListAllScreenP screenListAllUser;	
	private UserSendBugTrackEmailScreenP screenUserSendBugTrackEmail;	
	private OrganizerInsertScreenP screenInsertOrganizer;	
	private OrganizerUpdateScreenP screenUpdateOrganizer;	
	private OrganizerSearchScreenP screenSearchOrganizer;	
	private OrganizerRemoveScreenP screenRemoveOrganizer;	
	private OrganizerListAllScreenP screenListAllOrganizer;	
	private ReviewerInsertScreenP screenInsertReviewer;	
	private ReviewerUpdateScreenP screenUpdateReviewer;	
	private ReviewerSearchScreenP screenSearchReviewer;	
	private ReviewerRemoveScreenP screenRemoveReviewer;	
	private ReviewerListAllScreenP screenListAllReviewer;	
	private SpeakerInsertScreenP screenInsertSpeaker;	
	private SpeakerUpdateScreenP screenUpdateSpeaker;	
	private SpeakerSearchScreenP screenSearchSpeaker;	
	private SpeakerRemoveScreenP screenRemoveSpeaker;	
	private SpeakerListAllScreenP screenListAllSpeaker;	
	private EventInsertScreenP screenInsertEvent;	
	private EventUpdateScreenP screenUpdateEvent;	
	private EventSearchScreenP screenSearchEvent;	
	private EventRemoveScreenP screenRemoveEvent;	
	private EventListAllScreenP screenListAllEvent;	
	private EventManagementScreenP screenManagementEvent;	
	private EventProgramScreenP screenEventProgram;	
	private EventImportantDatesScreenP screenEventImportantDates;	
	private EventReportsFrequencyPerEventScreenP screenEventReportsFrequencyPerEvent;	
	private PaymentInsertScreenP screenInsertPayment;	
	private PaymentUpdateScreenP screenUpdatePayment;	
	private PaymentSearchScreenP screenSearchPayment;	
	private PaymentRemoveScreenP screenRemovePayment;	
	private PaymentListAllScreenP screenListAllPayment;	
	private PaymentManagementScreenP screenManagementPayment;	
	private ActivityInsertScreenP screenInsertActivity;	
	private ActivityUpdateScreenP screenUpdateActivity;	
	private ActivitySearchScreenP screenSearchActivity;	
	private ActivityRemoveScreenP screenRemoveActivity;	
	private ActivityListAllScreenP screenListAllActivity;	
	private ActivityManagementScreenP screenManagementActivity;	
	private ActivityReportsListOfAuthorsScreenP screenActivityReportsListOfAuthors;	
	private ActivityReportsFrequencyPerActivityScreenP screenActivityReportsFrequencyPerActivity;	
	private SubmissionSearchScreenP screenSearchSubmission;	
	private SubmissionRemoveScreenP screenRemoveSubmission;	
	private SubmissionListAllScreenP screenListAllSubmission;	
	private SubmissionCompleteInsertScreenP screenSubmissionCompleteInsert;	
	private SubmissionPartialInsertScreenP screenSubmissionPartialInsert;	
	private AssignmentInsertScreenP screenInsertAssignment;	
	private AssignmentSearchScreenP screenSearchAssignment;	
	private AssignmentRemoveScreenP screenRemoveAssignment;	
	private AssignmentListAllScreenP screenListAllAssignment;	
	private AssignmentManagementScreenP screenManagementAssignment;	
	private CheckingCopyInsertScreenP screenInsertCheckingCopy;	
	private CheckingCopyUpdateScreenP screenUpdateCheckingCopy;	
	private CheckingCopyRemoveScreenP screenRemoveCheckingCopy;	
	private CheckingCopySearchScreenP screenSearchCheckingCopy;	
	private CheckingCopyListAllScreenP screenListAllCheckingCopy;	
	private CheckingCopyManagementScreenP screenManagementCheckingCopy;	
	private NewOptionInsertScreenP screenInsertNewOption;	
	private NewOptionUpdateScreenP screenUpdateNewOption;	
	private NewOptionRemoveScreenP screenRemoveNewOption;	
	private NewOptionSearchScreenP screenSearchNewOption;	
	private NewOptionListAllScreenP screenListAllNewOption;	
	private ReceiptManagementScreenP screenManagementReceipt;	

	
	private ReviewInsertScreenP screenInsertReview;
	private ReviewRemoveScreenP screenRemoveReview;
	private ReviewUpdateScreenP screenUpdateReview;
	private ReviewSearchScreenP screenSearchReview;
	private ReviewListAllScreenP screenListAllReview;
	private ReviewManagementScreenP screenManagementReview;
	// private ReviewResultsScreenP screenResultsReview;

               
	private ActivityUserManagementScreenP screenManagementActivityUser;

	

               
	private ActivitySpeakerManagementScreenP screenManagementActivitySpeaker;

	


	


	


	


	

	private RegistrationInsertScreenP screenInsertRegistration;
	private RegistrationSearchScreenP screenSearchRegistration;
	private RegistrationListAllScreenP screenListAllRegistration;
	private RegistrationManagementScreenP screenManagementRegistration;
	private RegistrationUpdateScreenP screenUpdateRegistration;
	private RegistrationRemoveScreenP screenRemoveRegistration;
	
	private static JLabel labelImagem;
	
	private JDesktopPane desktopPane;
	
	
	public static RiseEventsFacade getFacade(){
		return RiseEventsFacade.getInstance();
	}
	
	public static RiseEventsMainScreenP getInstanceRiseEventsMainScreenP() {
		if (instanceRiseEventsMainScreenP == null) {
			RiseEventsMainScreenP.instanceRiseEventsMainScreenP = new RiseEventsMainScreenP();
		}
		return RiseEventsMainScreenP.instanceRiseEventsMainScreenP;
	}

	/**
	 * Launch the application.
	 */
	public static void main(String[] args) {
		EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					RiseEventsMainScreenP frame = new RiseEventsMainScreenP();
					frame.setVisible(true);
					
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});
	}

	/**
	 * Create the frame.
	 */
	public RiseEventsMainScreenP() {
		
		setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
		
		ExitMenuAction exitMenuAction = new ExitMenuAction();
		
		InsertUserMenuAction insertUserAction = new InsertUserMenuAction();	
		UpdateUserMenuAction updateUserAction = new UpdateUserMenuAction();	
		SearchUserMenuAction searchUserAction = new SearchUserMenuAction();	
		RemoveUserMenuAction removeUserAction = new RemoveUserMenuAction();	
		ListAllUserMenuAction listallUserAction = new ListAllUserMenuAction();	
		UserSendBugTrackEmailMenuAction userSendBugTrackEmailAction = new UserSendBugTrackEmailMenuAction();	
		InsertOrganizerMenuAction insertOrganizerAction = new InsertOrganizerMenuAction();	
		UpdateOrganizerMenuAction updateOrganizerAction = new UpdateOrganizerMenuAction();	
		SearchOrganizerMenuAction searchOrganizerAction = new SearchOrganizerMenuAction();	
		RemoveOrganizerMenuAction removeOrganizerAction = new RemoveOrganizerMenuAction();	
		ListAllOrganizerMenuAction listallOrganizerAction = new ListAllOrganizerMenuAction();	
		InsertReviewerMenuAction insertReviewerAction = new InsertReviewerMenuAction();	
		UpdateReviewerMenuAction updateReviewerAction = new UpdateReviewerMenuAction();	
		SearchReviewerMenuAction searchReviewerAction = new SearchReviewerMenuAction();	
		RemoveReviewerMenuAction removeReviewerAction = new RemoveReviewerMenuAction();	
		ListAllReviewerMenuAction listallReviewerAction = new ListAllReviewerMenuAction();	
		InsertSpeakerMenuAction insertSpeakerAction = new InsertSpeakerMenuAction();	
		UpdateSpeakerMenuAction updateSpeakerAction = new UpdateSpeakerMenuAction();	
		SearchSpeakerMenuAction searchSpeakerAction = new SearchSpeakerMenuAction();	
		RemoveSpeakerMenuAction removeSpeakerAction = new RemoveSpeakerMenuAction();	
		ListAllSpeakerMenuAction listallSpeakerAction = new ListAllSpeakerMenuAction();	
		InsertEventMenuAction insertEventAction = new InsertEventMenuAction();	
		UpdateEventMenuAction updateEventAction = new UpdateEventMenuAction();	
		SearchEventMenuAction searchEventAction = new SearchEventMenuAction();	
		RemoveEventMenuAction removeEventAction = new RemoveEventMenuAction();	
		ListAllEventMenuAction listallEventAction = new ListAllEventMenuAction();	
		ManagementEventMenuAction managementEventAction = new ManagementEventMenuAction();	
		EventProgramMenuAction eventProgramAction = new EventProgramMenuAction();	
		EventImportantDatesMenuAction eventImportantDatesAction = new EventImportantDatesMenuAction();	
		EventReportsFrequencyPerEventMenuAction eventReportsFrequencyPerEventAction = new EventReportsFrequencyPerEventMenuAction();	
		InsertPaymentMenuAction insertPaymentAction = new InsertPaymentMenuAction();	
		UpdatePaymentMenuAction updatePaymentAction = new UpdatePaymentMenuAction();	
		SearchPaymentMenuAction searchPaymentAction = new SearchPaymentMenuAction();	
		RemovePaymentMenuAction removePaymentAction = new RemovePaymentMenuAction();	
		ListAllPaymentMenuAction listallPaymentAction = new ListAllPaymentMenuAction();	
		ManagementPaymentMenuAction managementPaymentAction = new ManagementPaymentMenuAction();	
		InsertActivityMenuAction insertActivityAction = new InsertActivityMenuAction();	
		UpdateActivityMenuAction updateActivityAction = new UpdateActivityMenuAction();	
		SearchActivityMenuAction searchActivityAction = new SearchActivityMenuAction();	
		RemoveActivityMenuAction removeActivityAction = new RemoveActivityMenuAction();	
		ListAllActivityMenuAction listallActivityAction = new ListAllActivityMenuAction();	
		ManagementActivityMenuAction managementActivityAction = new ManagementActivityMenuAction();	
		ActivityReportsListOfAuthorsMenuAction activityReportsListOfAuthorsAction = new ActivityReportsListOfAuthorsMenuAction();	
		ActivityReportsFrequencyPerActivityMenuAction activityReportsFrequencyPerActivityAction = new ActivityReportsFrequencyPerActivityMenuAction();	
		SearchSubmissionMenuAction searchSubmissionAction = new SearchSubmissionMenuAction();	
		RemoveSubmissionMenuAction removeSubmissionAction = new RemoveSubmissionMenuAction();	
		ListAllSubmissionMenuAction listallSubmissionAction = new ListAllSubmissionMenuAction();	
		SubmissionCompleteInsertMenuAction submissionCompleteInsertAction = new SubmissionCompleteInsertMenuAction();	
		SubmissionPartialInsertMenuAction submissionPartialInsertAction = new SubmissionPartialInsertMenuAction();	
		InsertAssignmentMenuAction insertAssignmentAction = new InsertAssignmentMenuAction();	
		SearchAssignmentMenuAction searchAssignmentAction = new SearchAssignmentMenuAction();	
		RemoveAssignmentMenuAction removeAssignmentAction = new RemoveAssignmentMenuAction();	
		ListAllAssignmentMenuAction listallAssignmentAction = new ListAllAssignmentMenuAction();	
		ManagementAssignmentMenuAction managementAssignmentAction = new ManagementAssignmentMenuAction();	
		InsertCheckingCopyMenuAction insertCheckingCopyAction = new InsertCheckingCopyMenuAction();	
		UpdateCheckingCopyMenuAction updateCheckingCopyAction = new UpdateCheckingCopyMenuAction();	
		RemoveCheckingCopyMenuAction removeCheckingCopyAction = new RemoveCheckingCopyMenuAction();	
		SearchCheckingCopyMenuAction searchCheckingCopyAction = new SearchCheckingCopyMenuAction();	
		ListAllCheckingCopyMenuAction listallCheckingCopyAction = new ListAllCheckingCopyMenuAction();	
		ManagementCheckingCopyMenuAction managementCheckingCopyAction = new ManagementCheckingCopyMenuAction();	
		InsertNewOptionMenuAction insertNewOptionAction = new InsertNewOptionMenuAction();	
		UpdateNewOptionMenuAction updateNewOptionAction = new UpdateNewOptionMenuAction();	
		RemoveNewOptionMenuAction removeNewOptionAction = new RemoveNewOptionMenuAction();	
		SearchNewOptionMenuAction searchNewOptionAction = new SearchNewOptionMenuAction();	
		ListAllNewOptionMenuAction listallNewOptionAction = new ListAllNewOptionMenuAction();	
		ManagementReceiptMenuAction managementReceiptAction = new ManagementReceiptMenuAction();	

		RiseEventsMainScreenP.facade = RiseEventsFacade.getInstance();
		
		setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		setBounds(100, 100, 1120, 691);
		contentPane = new JPanel();
		contentPane.setBorder(new EmptyBorder(5, 5, 5, 5));
		setContentPane(contentPane);
		contentPane.setLayout(null);
		
		desktopPane = new JDesktopPane();
		desktopPane.setBackground(Color.LIGHT_GRAY);
		desktopPane.setBounds(6, 36, 1104, 624);
		contentPane.add(desktopPane);
		
		labelImagem = new JLabel("");
		labelImagem.setBounds(210, 164, 648, 193);
		ImageIcon image = new ImageIcon(getClass().getResource("/images/riseLabs.png"));
		Image imag = image.getImage().getScaledInstance(labelImagem.getWidth(), labelImagem.getHeight(), Image.SCALE_SMOOTH);
		labelImagem.setIcon(new ImageIcon(imag));
		desktopPane.add(labelImagem);
		
		JMenuBar menuBar = new JMenuBar();
		menuBar.setBounds(32, 12, 1078, 22);
		contentPane.add(menuBar);
		
		JMenu mnArchieve = new JMenu("Archieve");
		menuBar.add(mnArchieve);
		
		//#if ${Bugs} == "T"		
		// JMenuItem mntmBugtrack = new JMenuItem("Bugtrack");
		// mnArchieve.add(mntmBugtrack);
		//#endif
		
		JMenuItem mntmExit = new JMenuItem("Exit");
		mnArchieve.add(mntmExit);

		JMenu mnUser = new JMenu("User");
		menuBar.add(mnUser);
		JMenuItem mntmInsertUser = new JMenuItem("Insert");
		mnUser.add(mntmInsertUser);
		mntmInsertUser.addActionListener(insertUserAction);
		JMenuItem mntmUpdateUser = new JMenuItem("Update");
		mnUser.add(mntmUpdateUser);
		mntmUpdateUser.addActionListener(updateUserAction);
		JMenuItem mntmSearchUser = new JMenuItem("Search");
		mnUser.add(mntmSearchUser);
		mntmSearchUser.addActionListener(searchUserAction);
		JMenuItem mntmRemoveUser = new JMenuItem("Remove");
		mnUser.add(mntmRemoveUser);
		mntmRemoveUser.addActionListener(removeUserAction);
		JMenuItem mntmListAllUser = new JMenuItem("ListAll");
		mnUser.add(mntmListAllUser);
		mntmListAllUser.addActionListener(listallUserAction);
		JMenuItem mntmUserSendBugTrackEmail = new JMenuItem("sendBugTrackEmail");
		mnUser.add(mntmUserSendBugTrackEmail);
		mntmUserSendBugTrackEmail.addActionListener(userSendBugTrackEmailAction);
		JMenu mnOrganizer = new JMenu("Organizer");
		menuBar.add(mnOrganizer);
		JMenuItem mntmInsertOrganizer = new JMenuItem("Insert");
		mnOrganizer.add(mntmInsertOrganizer);
		mntmInsertOrganizer.addActionListener(insertOrganizerAction);
		JMenuItem mntmUpdateOrganizer = new JMenuItem("Update");
		mnOrganizer.add(mntmUpdateOrganizer);
		mntmUpdateOrganizer.addActionListener(updateOrganizerAction);
		JMenuItem mntmSearchOrganizer = new JMenuItem("Search");
		mnOrganizer.add(mntmSearchOrganizer);
		mntmSearchOrganizer.addActionListener(searchOrganizerAction);
		JMenuItem mntmRemoveOrganizer = new JMenuItem("Remove");
		mnOrganizer.add(mntmRemoveOrganizer);
		mntmRemoveOrganizer.addActionListener(removeOrganizerAction);
		JMenuItem mntmListAllOrganizer = new JMenuItem("ListAll");
		mnOrganizer.add(mntmListAllOrganizer);
		mntmListAllOrganizer.addActionListener(listallOrganizerAction);
		JMenu mnReviewer = new JMenu("Reviewer");
		menuBar.add(mnReviewer);
		JMenuItem mntmInsertReviewer = new JMenuItem("Insert");
		mnReviewer.add(mntmInsertReviewer);
		mntmInsertReviewer.addActionListener(insertReviewerAction);
		JMenuItem mntmUpdateReviewer = new JMenuItem("Update");
		mnReviewer.add(mntmUpdateReviewer);
		mntmUpdateReviewer.addActionListener(updateReviewerAction);
		JMenuItem mntmSearchReviewer = new JMenuItem("Search");
		mnReviewer.add(mntmSearchReviewer);
		mntmSearchReviewer.addActionListener(searchReviewerAction);
		JMenuItem mntmRemoveReviewer = new JMenuItem("Remove");
		mnReviewer.add(mntmRemoveReviewer);
		mntmRemoveReviewer.addActionListener(removeReviewerAction);
		JMenuItem mntmListAllReviewer = new JMenuItem("ListAll");
		mnReviewer.add(mntmListAllReviewer);
		mntmListAllReviewer.addActionListener(listallReviewerAction);
		JMenu mnSpeaker = new JMenu("Speaker");
		menuBar.add(mnSpeaker);
		JMenuItem mntmInsertSpeaker = new JMenuItem("Insert");
		mnSpeaker.add(mntmInsertSpeaker);
		mntmInsertSpeaker.addActionListener(insertSpeakerAction);
		JMenuItem mntmUpdateSpeaker = new JMenuItem("Update");
		mnSpeaker.add(mntmUpdateSpeaker);
		mntmUpdateSpeaker.addActionListener(updateSpeakerAction);
		JMenuItem mntmSearchSpeaker = new JMenuItem("Search");
		mnSpeaker.add(mntmSearchSpeaker);
		mntmSearchSpeaker.addActionListener(searchSpeakerAction);
		JMenuItem mntmRemoveSpeaker = new JMenuItem("Remove");
		mnSpeaker.add(mntmRemoveSpeaker);
		mntmRemoveSpeaker.addActionListener(removeSpeakerAction);
		JMenuItem mntmListAllSpeaker = new JMenuItem("ListAll");
		mnSpeaker.add(mntmListAllSpeaker);
		mntmListAllSpeaker.addActionListener(listallSpeakerAction);
		JMenu mnEvent = new JMenu("Event");
		menuBar.add(mnEvent);
		JMenuItem mntmInsertEvent = new JMenuItem("Insert");
		mnEvent.add(mntmInsertEvent);
		mntmInsertEvent.addActionListener(insertEventAction);
		JMenuItem mntmUpdateEvent = new JMenuItem("Update");
		mnEvent.add(mntmUpdateEvent);
		mntmUpdateEvent.addActionListener(updateEventAction);
		JMenuItem mntmSearchEvent = new JMenuItem("Search");
		mnEvent.add(mntmSearchEvent);
		mntmSearchEvent.addActionListener(searchEventAction);
		JMenuItem mntmRemoveEvent = new JMenuItem("Remove");
		mnEvent.add(mntmRemoveEvent);
		mntmRemoveEvent.addActionListener(removeEventAction);
		JMenuItem mntmListAllEvent = new JMenuItem("ListAll");
		mnEvent.add(mntmListAllEvent);
		mntmListAllEvent.addActionListener(listallEventAction);
		JMenuItem mntmManagementEvent = new JMenuItem("Management");
		mnEvent.add(mntmManagementEvent);
		mntmManagementEvent.addActionListener(managementEventAction);
		JMenuItem mntmEventProgram = new JMenuItem("program");
		mnEvent.add(mntmEventProgram);
		mntmEventProgram.addActionListener(eventProgramAction);
		JMenuItem mntmEventImportantDates = new JMenuItem("importantDates");
		mnEvent.add(mntmEventImportantDates);
		mntmEventImportantDates.addActionListener(eventImportantDatesAction);
		JMenuItem mntmEventReportsFrequencyPerEvent = new JMenuItem("reportsFrequencyPerEvent");
		mnEvent.add(mntmEventReportsFrequencyPerEvent);
		mntmEventReportsFrequencyPerEvent.addActionListener(eventReportsFrequencyPerEventAction);
		JMenu mnPayment = new JMenu("Payment");
		menuBar.add(mnPayment);
		JMenuItem mntmInsertPayment = new JMenuItem("Insert");
		mnPayment.add(mntmInsertPayment);
		mntmInsertPayment.addActionListener(insertPaymentAction);
		JMenuItem mntmUpdatePayment = new JMenuItem("Update");
		mnPayment.add(mntmUpdatePayment);
		mntmUpdatePayment.addActionListener(updatePaymentAction);
		JMenuItem mntmSearchPayment = new JMenuItem("Search");
		mnPayment.add(mntmSearchPayment);
		mntmSearchPayment.addActionListener(searchPaymentAction);
		JMenuItem mntmRemovePayment = new JMenuItem("Remove");
		mnPayment.add(mntmRemovePayment);
		mntmRemovePayment.addActionListener(removePaymentAction);
		JMenuItem mntmListAllPayment = new JMenuItem("ListAll");
		mnPayment.add(mntmListAllPayment);
		mntmListAllPayment.addActionListener(listallPaymentAction);
		JMenuItem mntmManagementPayment = new JMenuItem("Management");
		mnPayment.add(mntmManagementPayment);
		mntmManagementPayment.addActionListener(managementPaymentAction);
		JMenu mnActivity = new JMenu("Activity");
		menuBar.add(mnActivity);
		JMenuItem mntmInsertActivity = new JMenuItem("Insert");
		mnActivity.add(mntmInsertActivity);
		mntmInsertActivity.addActionListener(insertActivityAction);
		JMenuItem mntmUpdateActivity = new JMenuItem("Update");
		mnActivity.add(mntmUpdateActivity);
		mntmUpdateActivity.addActionListener(updateActivityAction);
		JMenuItem mntmSearchActivity = new JMenuItem("Search");
		mnActivity.add(mntmSearchActivity);
		mntmSearchActivity.addActionListener(searchActivityAction);
		JMenuItem mntmRemoveActivity = new JMenuItem("Remove");
		mnActivity.add(mntmRemoveActivity);
		mntmRemoveActivity.addActionListener(removeActivityAction);
		JMenuItem mntmListAllActivity = new JMenuItem("ListAll");
		mnActivity.add(mntmListAllActivity);
		mntmListAllActivity.addActionListener(listallActivityAction);
		JMenuItem mntmManagementActivity = new JMenuItem("Management");
		mnActivity.add(mntmManagementActivity);
		mntmManagementActivity.addActionListener(managementActivityAction);
		JMenuItem mntmActivityReportsListOfAuthors = new JMenuItem("reportsListOfAuthors");
		mnActivity.add(mntmActivityReportsListOfAuthors);
		mntmActivityReportsListOfAuthors.addActionListener(activityReportsListOfAuthorsAction);
		JMenuItem mntmActivityReportsFrequencyPerActivity = new JMenuItem("reportsFrequencyPerActivity");
		mnActivity.add(mntmActivityReportsFrequencyPerActivity);
		mntmActivityReportsFrequencyPerActivity.addActionListener(activityReportsFrequencyPerActivityAction);
		JMenu mnSubmission = new JMenu("Submission");
		menuBar.add(mnSubmission);
		JMenuItem mntmSearchSubmission = new JMenuItem("Search");
		mnSubmission.add(mntmSearchSubmission);
		mntmSearchSubmission.addActionListener(searchSubmissionAction);
		JMenuItem mntmRemoveSubmission = new JMenuItem("Remove");
		mnSubmission.add(mntmRemoveSubmission);
		mntmRemoveSubmission.addActionListener(removeSubmissionAction);
		JMenuItem mntmListAllSubmission = new JMenuItem("ListAll");
		mnSubmission.add(mntmListAllSubmission);
		mntmListAllSubmission.addActionListener(listallSubmissionAction);
		JMenuItem mntmSubmissionCompleteInsert = new JMenuItem("completeInsert");
		mnSubmission.add(mntmSubmissionCompleteInsert);
		mntmSubmissionCompleteInsert.addActionListener(submissionCompleteInsertAction);
		JMenuItem mntmSubmissionPartialInsert = new JMenuItem("partialInsert");
		mnSubmission.add(mntmSubmissionPartialInsert);
		mntmSubmissionPartialInsert.addActionListener(submissionPartialInsertAction);
		JMenu mnAuthor = new JMenu("Author");
		menuBar.add(mnAuthor);
		JMenu mnAssignment = new JMenu("Assignment");
		menuBar.add(mnAssignment);
		JMenuItem mntmInsertAssignment = new JMenuItem("Insert");
		mnAssignment.add(mntmInsertAssignment);
		mntmInsertAssignment.addActionListener(insertAssignmentAction);
		JMenuItem mntmSearchAssignment = new JMenuItem("Search");
		mnAssignment.add(mntmSearchAssignment);
		mntmSearchAssignment.addActionListener(searchAssignmentAction);
		JMenuItem mntmRemoveAssignment = new JMenuItem("Remove");
		mnAssignment.add(mntmRemoveAssignment);
		mntmRemoveAssignment.addActionListener(removeAssignmentAction);
		JMenuItem mntmListAllAssignment = new JMenuItem("ListAll");
		mnAssignment.add(mntmListAllAssignment);
		mntmListAllAssignment.addActionListener(listallAssignmentAction);
		JMenuItem mntmManagementAssignment = new JMenuItem("Management");
		mnAssignment.add(mntmManagementAssignment);
		mntmManagementAssignment.addActionListener(managementAssignmentAction);
		JMenu mnCheckingCopy = new JMenu("CheckingCopy");
		menuBar.add(mnCheckingCopy);
		JMenuItem mntmInsertCheckingCopy = new JMenuItem("Insert");
		mnCheckingCopy.add(mntmInsertCheckingCopy);
		mntmInsertCheckingCopy.addActionListener(insertCheckingCopyAction);
		JMenuItem mntmUpdateCheckingCopy = new JMenuItem("Update");
		mnCheckingCopy.add(mntmUpdateCheckingCopy);
		mntmUpdateCheckingCopy.addActionListener(updateCheckingCopyAction);
		JMenuItem mntmRemoveCheckingCopy = new JMenuItem("Remove");
		mnCheckingCopy.add(mntmRemoveCheckingCopy);
		mntmRemoveCheckingCopy.addActionListener(removeCheckingCopyAction);
		JMenuItem mntmSearchCheckingCopy = new JMenuItem("Search");
		mnCheckingCopy.add(mntmSearchCheckingCopy);
		mntmSearchCheckingCopy.addActionListener(searchCheckingCopyAction);
		JMenuItem mntmListAllCheckingCopy = new JMenuItem("ListAll");
		mnCheckingCopy.add(mntmListAllCheckingCopy);
		mntmListAllCheckingCopy.addActionListener(listallCheckingCopyAction);
		JMenuItem mntmManagementCheckingCopy = new JMenuItem("Management");
		mnCheckingCopy.add(mntmManagementCheckingCopy);
		mntmManagementCheckingCopy.addActionListener(managementCheckingCopyAction);
		JMenu mnNewOption = new JMenu("NewOption");
		menuBar.add(mnNewOption);
		JMenuItem mntmInsertNewOption = new JMenuItem("Insert");
		mnNewOption.add(mntmInsertNewOption);
		mntmInsertNewOption.addActionListener(insertNewOptionAction);
		JMenuItem mntmUpdateNewOption = new JMenuItem("Update");
		mnNewOption.add(mntmUpdateNewOption);
		mntmUpdateNewOption.addActionListener(updateNewOptionAction);
		JMenuItem mntmRemoveNewOption = new JMenuItem("Remove");
		mnNewOption.add(mntmRemoveNewOption);
		mntmRemoveNewOption.addActionListener(removeNewOptionAction);
		JMenuItem mntmSearchNewOption = new JMenuItem("Search");
		mnNewOption.add(mntmSearchNewOption);
		mntmSearchNewOption.addActionListener(searchNewOptionAction);
		JMenuItem mntmListAllNewOption = new JMenuItem("ListAll");
		mnNewOption.add(mntmListAllNewOption);
		mntmListAllNewOption.addActionListener(listallNewOptionAction);
		JMenu mnReceipt = new JMenu("Receipt");
		menuBar.add(mnReceipt);
		JMenuItem mntmManagementReceipt = new JMenuItem("Management");
		mnReceipt.add(mntmManagementReceipt);
		mntmManagementReceipt.addActionListener(managementReceiptAction);
		JMenu mnReports = new JMenu("Reports");
		menuBar.add(mnReports);
		
		mntmExit.addActionListener(exitMenuAction);
	}
	
	private class ExitMenuAction  implements ActionListener{ 

		@Override
		public void actionPerformed(ActionEvent e) {
			dispose();
		}
	} 

	private class InsertUserMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertUser = UserInsertScreenP.getInstanceUserInsertScreenP();
			if(screenInsertUser.getParent() == null){
				desktopPane.add(screenInsertUser);
			}
			screenInsertUser.setVisible(true);
			desktopPane.moveToFront(screenInsertUser);
			try {
				screenInsertUser.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateUserMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateUser = UserUpdateScreenP.getInstanceUserUpdateScreenP();
			if(screenUpdateUser.getParent() == null){
				desktopPane.add(screenUpdateUser);
			}
			screenUpdateUser.setVisible(true);
			desktopPane.moveToFront(screenUpdateUser);
			try {
				screenUpdateUser.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchUserMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchUser = UserSearchScreenP.getInstanceUserSearchScreenP();
			if(screenSearchUser.getParent() == null){
				desktopPane.add(screenSearchUser);
			}
			screenSearchUser.setVisible(true);
			desktopPane.moveToFront(screenSearchUser);
			try {
				screenSearchUser.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveUserMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveUser = UserRemoveScreenP.getInstanceUserRemoveScreenP();
			if(screenRemoveUser.getParent() == null){
				desktopPane.add(screenRemoveUser);
			}
			screenRemoveUser.setVisible(true);
			desktopPane.moveToFront(screenRemoveUser);
			try {
				screenRemoveUser.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllUserMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllUser = UserListAllScreenP.getInstanceUserListAllScreenP();
			if(screenListAllUser.getParent() == null){
				desktopPane.add(screenListAllUser);
			}
			screenListAllUser.setVisible(true);
			desktopPane.moveToFront(screenListAllUser);
			try {
				screenListAllUser.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
			private class UserSendBugTrackEmailMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenUserSendBugTrackEmail = UserSendBugTrackEmailScreenP.getInstanceUserSendBugTrackEmailScreenP();
				if(screenUserSendBugTrackEmail.getParent() == null){
					desktopPane.add(screenUserSendBugTrackEmail);
				}
				screenUserSendBugTrackEmail.setVisible(true);
				desktopPane.moveToFront(screenUserSendBugTrackEmail);
				try {
					screenUserSendBugTrackEmail.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
	private class InsertOrganizerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertOrganizer = OrganizerInsertScreenP.getInstanceOrganizerInsertScreenP();
			if(screenInsertOrganizer.getParent() == null){
				desktopPane.add(screenInsertOrganizer);
			}
			screenInsertOrganizer.setVisible(true);
			desktopPane.moveToFront(screenInsertOrganizer);
			try {
				screenInsertOrganizer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateOrganizerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateOrganizer = OrganizerUpdateScreenP.getInstanceOrganizerUpdateScreenP();
			if(screenUpdateOrganizer.getParent() == null){
				desktopPane.add(screenUpdateOrganizer);
			}
			screenUpdateOrganizer.setVisible(true);
			desktopPane.moveToFront(screenUpdateOrganizer);
			try {
				screenUpdateOrganizer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchOrganizerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchOrganizer = OrganizerSearchScreenP.getInstanceOrganizerSearchScreenP();
			if(screenSearchOrganizer.getParent() == null){
				desktopPane.add(screenSearchOrganizer);
			}
			screenSearchOrganizer.setVisible(true);
			desktopPane.moveToFront(screenSearchOrganizer);
			try {
				screenSearchOrganizer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveOrganizerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveOrganizer = OrganizerRemoveScreenP.getInstanceOrganizerRemoveScreenP();
			if(screenRemoveOrganizer.getParent() == null){
				desktopPane.add(screenRemoveOrganizer);
			}
			screenRemoveOrganizer.setVisible(true);
			desktopPane.moveToFront(screenRemoveOrganizer);
			try {
				screenRemoveOrganizer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllOrganizerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllOrganizer = OrganizerListAllScreenP.getInstanceOrganizerListAllScreenP();
			if(screenListAllOrganizer.getParent() == null){
				desktopPane.add(screenListAllOrganizer);
			}
			screenListAllOrganizer.setVisible(true);
			desktopPane.moveToFront(screenListAllOrganizer);
			try {
				screenListAllOrganizer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertReviewerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertReviewer = ReviewerInsertScreenP.getInstanceReviewerInsertScreenP();
			if(screenInsertReviewer.getParent() == null){
				desktopPane.add(screenInsertReviewer);
			}
			screenInsertReviewer.setVisible(true);
			desktopPane.moveToFront(screenInsertReviewer);
			try {
				screenInsertReviewer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateReviewerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateReviewer = ReviewerUpdateScreenP.getInstanceReviewerUpdateScreenP();
			if(screenUpdateReviewer.getParent() == null){
				desktopPane.add(screenUpdateReviewer);
			}
			screenUpdateReviewer.setVisible(true);
			desktopPane.moveToFront(screenUpdateReviewer);
			try {
				screenUpdateReviewer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchReviewerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchReviewer = ReviewerSearchScreenP.getInstanceReviewerSearchScreenP();
			if(screenSearchReviewer.getParent() == null){
				desktopPane.add(screenSearchReviewer);
			}
			screenSearchReviewer.setVisible(true);
			desktopPane.moveToFront(screenSearchReviewer);
			try {
				screenSearchReviewer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveReviewerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveReviewer = ReviewerRemoveScreenP.getInstanceReviewerRemoveScreenP();
			if(screenRemoveReviewer.getParent() == null){
				desktopPane.add(screenRemoveReviewer);
			}
			screenRemoveReviewer.setVisible(true);
			desktopPane.moveToFront(screenRemoveReviewer);
			try {
				screenRemoveReviewer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllReviewerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllReviewer = ReviewerListAllScreenP.getInstanceReviewerListAllScreenP();
			if(screenListAllReviewer.getParent() == null){
				desktopPane.add(screenListAllReviewer);
			}
			screenListAllReviewer.setVisible(true);
			desktopPane.moveToFront(screenListAllReviewer);
			try {
				screenListAllReviewer.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertSpeakerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertSpeaker = SpeakerInsertScreenP.getInstanceSpeakerInsertScreenP();
			if(screenInsertSpeaker.getParent() == null){
				desktopPane.add(screenInsertSpeaker);
			}
			screenInsertSpeaker.setVisible(true);
			desktopPane.moveToFront(screenInsertSpeaker);
			try {
				screenInsertSpeaker.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateSpeakerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateSpeaker = SpeakerUpdateScreenP.getInstanceSpeakerUpdateScreenP();
			if(screenUpdateSpeaker.getParent() == null){
				desktopPane.add(screenUpdateSpeaker);
			}
			screenUpdateSpeaker.setVisible(true);
			desktopPane.moveToFront(screenUpdateSpeaker);
			try {
				screenUpdateSpeaker.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchSpeakerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchSpeaker = SpeakerSearchScreenP.getInstanceSpeakerSearchScreenP();
			if(screenSearchSpeaker.getParent() == null){
				desktopPane.add(screenSearchSpeaker);
			}
			screenSearchSpeaker.setVisible(true);
			desktopPane.moveToFront(screenSearchSpeaker);
			try {
				screenSearchSpeaker.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveSpeakerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveSpeaker = SpeakerRemoveScreenP.getInstanceSpeakerRemoveScreenP();
			if(screenRemoveSpeaker.getParent() == null){
				desktopPane.add(screenRemoveSpeaker);
			}
			screenRemoveSpeaker.setVisible(true);
			desktopPane.moveToFront(screenRemoveSpeaker);
			try {
				screenRemoveSpeaker.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllSpeakerMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllSpeaker = SpeakerListAllScreenP.getInstanceSpeakerListAllScreenP();
			if(screenListAllSpeaker.getParent() == null){
				desktopPane.add(screenListAllSpeaker);
			}
			screenListAllSpeaker.setVisible(true);
			desktopPane.moveToFront(screenListAllSpeaker);
			try {
				screenListAllSpeaker.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertEvent = EventInsertScreenP.getInstanceEventInsertScreenP();
			if(screenInsertEvent.getParent() == null){
				desktopPane.add(screenInsertEvent);
			}
			screenInsertEvent.setVisible(true);
			desktopPane.moveToFront(screenInsertEvent);
			try {
				screenInsertEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateEvent = EventUpdateScreenP.getInstanceEventUpdateScreenP();
			if(screenUpdateEvent.getParent() == null){
				desktopPane.add(screenUpdateEvent);
			}
			screenUpdateEvent.setVisible(true);
			desktopPane.moveToFront(screenUpdateEvent);
			try {
				screenUpdateEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchEvent = EventSearchScreenP.getInstanceEventSearchScreenP();
			if(screenSearchEvent.getParent() == null){
				desktopPane.add(screenSearchEvent);
			}
			screenSearchEvent.setVisible(true);
			desktopPane.moveToFront(screenSearchEvent);
			try {
				screenSearchEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveEvent = EventRemoveScreenP.getInstanceEventRemoveScreenP();
			if(screenRemoveEvent.getParent() == null){
				desktopPane.add(screenRemoveEvent);
			}
			screenRemoveEvent.setVisible(true);
			desktopPane.moveToFront(screenRemoveEvent);
			try {
				screenRemoveEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllEvent = EventListAllScreenP.getInstanceEventListAllScreenP();
			if(screenListAllEvent.getParent() == null){
				desktopPane.add(screenListAllEvent);
			}
			screenListAllEvent.setVisible(true);
			desktopPane.moveToFront(screenListAllEvent);
			try {
				screenListAllEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementEventMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementEvent = EventManagementScreenP.getInstanceEventManagementScreenP();
			if(screenManagementEvent.getParent() == null){
				desktopPane.add(screenManagementEvent);
			}
			screenManagementEvent.setVisible(true);
			desktopPane.moveToFront(screenManagementEvent);
			try {
				screenManagementEvent.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
			private class EventProgramMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenEventProgram = EventProgramScreenP.getInstanceEventProgramScreenP();
				if(screenEventProgram.getParent() == null){
					desktopPane.add(screenEventProgram);
				}
				screenEventProgram.setVisible(true);
				desktopPane.moveToFront(screenEventProgram);
				try {
					screenEventProgram.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
			private class EventImportantDatesMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenEventImportantDates = EventImportantDatesScreenP.getInstanceEventImportantDatesScreenP();
				if(screenEventImportantDates.getParent() == null){
					desktopPane.add(screenEventImportantDates);
				}
				screenEventImportantDates.setVisible(true);
				desktopPane.moveToFront(screenEventImportantDates);
				try {
					screenEventImportantDates.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
			private class EventReportsFrequencyPerEventMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenEventReportsFrequencyPerEvent = EventReportsFrequencyPerEventScreenP.getInstanceEventReportsFrequencyPerEventScreenP();
				if(screenEventReportsFrequencyPerEvent.getParent() == null){
					desktopPane.add(screenEventReportsFrequencyPerEvent);
				}
				screenEventReportsFrequencyPerEvent.setVisible(true);
				desktopPane.moveToFront(screenEventReportsFrequencyPerEvent);
				try {
					screenEventReportsFrequencyPerEvent.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
	private class InsertPaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertPayment = PaymentInsertScreenP.getInstancePaymentInsertScreenP();
			if(screenInsertPayment.getParent() == null){
				desktopPane.add(screenInsertPayment);
			}
			screenInsertPayment.setVisible(true);
			desktopPane.moveToFront(screenInsertPayment);
			try {
				screenInsertPayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdatePaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdatePayment = PaymentUpdateScreenP.getInstancePaymentUpdateScreenP();
			if(screenUpdatePayment.getParent() == null){
				desktopPane.add(screenUpdatePayment);
			}
			screenUpdatePayment.setVisible(true);
			desktopPane.moveToFront(screenUpdatePayment);
			try {
				screenUpdatePayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchPaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchPayment = PaymentSearchScreenP.getInstancePaymentSearchScreenP();
			if(screenSearchPayment.getParent() == null){
				desktopPane.add(screenSearchPayment);
			}
			screenSearchPayment.setVisible(true);
			desktopPane.moveToFront(screenSearchPayment);
			try {
				screenSearchPayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemovePaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemovePayment = PaymentRemoveScreenP.getInstancePaymentRemoveScreenP();
			if(screenRemovePayment.getParent() == null){
				desktopPane.add(screenRemovePayment);
			}
			screenRemovePayment.setVisible(true);
			desktopPane.moveToFront(screenRemovePayment);
			try {
				screenRemovePayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllPaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllPayment = PaymentListAllScreenP.getInstancePaymentListAllScreenP();
			if(screenListAllPayment.getParent() == null){
				desktopPane.add(screenListAllPayment);
			}
			screenListAllPayment.setVisible(true);
			desktopPane.moveToFront(screenListAllPayment);
			try {
				screenListAllPayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementPaymentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementPayment = PaymentManagementScreenP.getInstancePaymentManagementScreenP();
			if(screenManagementPayment.getParent() == null){
				desktopPane.add(screenManagementPayment);
			}
			screenManagementPayment.setVisible(true);
			desktopPane.moveToFront(screenManagementPayment);
			try {
				screenManagementPayment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertActivity = ActivityInsertScreenP.getInstanceActivityInsertScreenP();
			if(screenInsertActivity.getParent() == null){
				desktopPane.add(screenInsertActivity);
			}
			screenInsertActivity.setVisible(true);
			desktopPane.moveToFront(screenInsertActivity);
			try {
				screenInsertActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateActivity = ActivityUpdateScreenP.getInstanceActivityUpdateScreenP();
			if(screenUpdateActivity.getParent() == null){
				desktopPane.add(screenUpdateActivity);
			}
			screenUpdateActivity.setVisible(true);
			desktopPane.moveToFront(screenUpdateActivity);
			try {
				screenUpdateActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchActivity = ActivitySearchScreenP.getInstanceActivitySearchScreenP();
			if(screenSearchActivity.getParent() == null){
				desktopPane.add(screenSearchActivity);
			}
			screenSearchActivity.setVisible(true);
			desktopPane.moveToFront(screenSearchActivity);
			try {
				screenSearchActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveActivity = ActivityRemoveScreenP.getInstanceActivityRemoveScreenP();
			if(screenRemoveActivity.getParent() == null){
				desktopPane.add(screenRemoveActivity);
			}
			screenRemoveActivity.setVisible(true);
			desktopPane.moveToFront(screenRemoveActivity);
			try {
				screenRemoveActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllActivity = ActivityListAllScreenP.getInstanceActivityListAllScreenP();
			if(screenListAllActivity.getParent() == null){
				desktopPane.add(screenListAllActivity);
			}
			screenListAllActivity.setVisible(true);
			desktopPane.moveToFront(screenListAllActivity);
			try {
				screenListAllActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementActivityMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementActivity = ActivityManagementScreenP.getInstanceActivityManagementScreenP();
			if(screenManagementActivity.getParent() == null){
				desktopPane.add(screenManagementActivity);
			}
			screenManagementActivity.setVisible(true);
			desktopPane.moveToFront(screenManagementActivity);
			try {
				screenManagementActivity.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
			private class ActivityReportsListOfAuthorsMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenActivityReportsListOfAuthors = ActivityReportsListOfAuthorsScreenP.getInstanceActivityReportsListOfAuthorsScreenP();
				if(screenActivityReportsListOfAuthors.getParent() == null){
					desktopPane.add(screenActivityReportsListOfAuthors);
				}
				screenActivityReportsListOfAuthors.setVisible(true);
				desktopPane.moveToFront(screenActivityReportsListOfAuthors);
				try {
					screenActivityReportsListOfAuthors.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
			private class ActivityReportsFrequencyPerActivityMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenActivityReportsFrequencyPerActivity = ActivityReportsFrequencyPerActivityScreenP.getInstanceActivityReportsFrequencyPerActivityScreenP();
				if(screenActivityReportsFrequencyPerActivity.getParent() == null){
					desktopPane.add(screenActivityReportsFrequencyPerActivity);
				}
				screenActivityReportsFrequencyPerActivity.setVisible(true);
				desktopPane.moveToFront(screenActivityReportsFrequencyPerActivity);
				try {
					screenActivityReportsFrequencyPerActivity.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
	private class SearchSubmissionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchSubmission = SubmissionSearchScreenP.getInstanceSubmissionSearchScreenP();
			if(screenSearchSubmission.getParent() == null){
				desktopPane.add(screenSearchSubmission);
			}
			screenSearchSubmission.setVisible(true);
			desktopPane.moveToFront(screenSearchSubmission);
			try {
				screenSearchSubmission.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveSubmissionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveSubmission = SubmissionRemoveScreenP.getInstanceSubmissionRemoveScreenP();
			if(screenRemoveSubmission.getParent() == null){
				desktopPane.add(screenRemoveSubmission);
			}
			screenRemoveSubmission.setVisible(true);
			desktopPane.moveToFront(screenRemoveSubmission);
			try {
				screenRemoveSubmission.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllSubmissionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllSubmission = SubmissionListAllScreenP.getInstanceSubmissionListAllScreenP();
			if(screenListAllSubmission.getParent() == null){
				desktopPane.add(screenListAllSubmission);
			}
			screenListAllSubmission.setVisible(true);
			desktopPane.moveToFront(screenListAllSubmission);
			try {
				screenListAllSubmission.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
			private class SubmissionCompleteInsertMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenSubmissionCompleteInsert = SubmissionCompleteInsertScreenP.getInstanceSubmissionCompleteInsertScreenP();
				if(screenSubmissionCompleteInsert.getParent() == null){
					desktopPane.add(screenSubmissionCompleteInsert);
				}
				screenSubmissionCompleteInsert.setVisible(true);
				desktopPane.moveToFront(screenSubmissionCompleteInsert);
				try {
					screenSubmissionCompleteInsert.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
			private class SubmissionPartialInsertMenuAction implements ActionListener{
			@Override
			public void actionPerformed(ActionEvent e) {
				screenSubmissionPartialInsert = SubmissionPartialInsertScreenP.getInstanceSubmissionPartialInsertScreenP();
				if(screenSubmissionPartialInsert.getParent() == null){
					desktopPane.add(screenSubmissionPartialInsert);
				}
				screenSubmissionPartialInsert.setVisible(true);
				desktopPane.moveToFront(screenSubmissionPartialInsert);
				try {
					screenSubmissionPartialInsert.setSelected(true);
				} catch (PropertyVetoException e1) {
					e1.printStackTrace();
					}
				}  
			}
	private class InsertAssignmentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertAssignment = AssignmentInsertScreenP.getInstanceAssignmentInsertScreenP();
			if(screenInsertAssignment.getParent() == null){
				desktopPane.add(screenInsertAssignment);
			}
			screenInsertAssignment.setVisible(true);
			desktopPane.moveToFront(screenInsertAssignment);
			try {
				screenInsertAssignment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchAssignmentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchAssignment = AssignmentSearchScreenP.getInstanceAssignmentSearchScreenP();
			if(screenSearchAssignment.getParent() == null){
				desktopPane.add(screenSearchAssignment);
			}
			screenSearchAssignment.setVisible(true);
			desktopPane.moveToFront(screenSearchAssignment);
			try {
				screenSearchAssignment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveAssignmentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveAssignment = AssignmentRemoveScreenP.getInstanceAssignmentRemoveScreenP();
			if(screenRemoveAssignment.getParent() == null){
				desktopPane.add(screenRemoveAssignment);
			}
			screenRemoveAssignment.setVisible(true);
			desktopPane.moveToFront(screenRemoveAssignment);
			try {
				screenRemoveAssignment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllAssignmentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllAssignment = AssignmentListAllScreenP.getInstanceAssignmentListAllScreenP();
			if(screenListAllAssignment.getParent() == null){
				desktopPane.add(screenListAllAssignment);
			}
			screenListAllAssignment.setVisible(true);
			desktopPane.moveToFront(screenListAllAssignment);
			try {
				screenListAllAssignment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementAssignmentMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementAssignment = AssignmentManagementScreenP.getInstanceAssignmentManagementScreenP();
			if(screenManagementAssignment.getParent() == null){
				desktopPane.add(screenManagementAssignment);
			}
			screenManagementAssignment.setVisible(true);
			desktopPane.moveToFront(screenManagementAssignment);
			try {
				screenManagementAssignment.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertCheckingCopy = CheckingCopyInsertScreenP.getInstanceCheckingCopyInsertScreenP();
			if(screenInsertCheckingCopy.getParent() == null){
				desktopPane.add(screenInsertCheckingCopy);
			}
			screenInsertCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenInsertCheckingCopy);
			try {
				screenInsertCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateCheckingCopy = CheckingCopyUpdateScreenP.getInstanceCheckingCopyUpdateScreenP();
			if(screenUpdateCheckingCopy.getParent() == null){
				desktopPane.add(screenUpdateCheckingCopy);
			}
			screenUpdateCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenUpdateCheckingCopy);
			try {
				screenUpdateCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveCheckingCopy = CheckingCopyRemoveScreenP.getInstanceCheckingCopyRemoveScreenP();
			if(screenRemoveCheckingCopy.getParent() == null){
				desktopPane.add(screenRemoveCheckingCopy);
			}
			screenRemoveCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenRemoveCheckingCopy);
			try {
				screenRemoveCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchCheckingCopy = CheckingCopySearchScreenP.getInstanceCheckingCopySearchScreenP();
			if(screenSearchCheckingCopy.getParent() == null){
				desktopPane.add(screenSearchCheckingCopy);
			}
			screenSearchCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenSearchCheckingCopy);
			try {
				screenSearchCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllCheckingCopy = CheckingCopyListAllScreenP.getInstanceCheckingCopyListAllScreenP();
			if(screenListAllCheckingCopy.getParent() == null){
				desktopPane.add(screenListAllCheckingCopy);
			}
			screenListAllCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenListAllCheckingCopy);
			try {
				screenListAllCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementCheckingCopyMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementCheckingCopy = CheckingCopyManagementScreenP.getInstanceCheckingCopyManagementScreenP();
			if(screenManagementCheckingCopy.getParent() == null){
				desktopPane.add(screenManagementCheckingCopy);
			}
			screenManagementCheckingCopy.setVisible(true);
			desktopPane.moveToFront(screenManagementCheckingCopy);
			try {
				screenManagementCheckingCopy.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class InsertNewOptionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenInsertNewOption = NewOptionInsertScreenP.getInstanceNewOptionInsertScreenP();
			if(screenInsertNewOption.getParent() == null){
				desktopPane.add(screenInsertNewOption);
			}
			screenInsertNewOption.setVisible(true);
			desktopPane.moveToFront(screenInsertNewOption);
			try {
				screenInsertNewOption.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class UpdateNewOptionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenUpdateNewOption = NewOptionUpdateScreenP.getInstanceNewOptionUpdateScreenP();
			if(screenUpdateNewOption.getParent() == null){
				desktopPane.add(screenUpdateNewOption);
			}
			screenUpdateNewOption.setVisible(true);
			desktopPane.moveToFront(screenUpdateNewOption);
			try {
				screenUpdateNewOption.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class RemoveNewOptionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenRemoveNewOption = NewOptionRemoveScreenP.getInstanceNewOptionRemoveScreenP();
			if(screenRemoveNewOption.getParent() == null){
				desktopPane.add(screenRemoveNewOption);
			}
			screenRemoveNewOption.setVisible(true);
			desktopPane.moveToFront(screenRemoveNewOption);
			try {
				screenRemoveNewOption.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class SearchNewOptionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenSearchNewOption = NewOptionSearchScreenP.getInstanceNewOptionSearchScreenP();
			if(screenSearchNewOption.getParent() == null){
				desktopPane.add(screenSearchNewOption);
			}
			screenSearchNewOption.setVisible(true);
			desktopPane.moveToFront(screenSearchNewOption);
			try {
				screenSearchNewOption.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ListAllNewOptionMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenListAllNewOption = NewOptionListAllScreenP.getInstanceNewOptionListAllScreenP();
			if(screenListAllNewOption.getParent() == null){
				desktopPane.add(screenListAllNewOption);
			}
			screenListAllNewOption.setVisible(true);
			desktopPane.moveToFront(screenListAllNewOption);
			try {
				screenListAllNewOption.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
	private class ManagementReceiptMenuAction implements ActionListener{ 
		@Override
		public void actionPerformed(ActionEvent e) {
			
			screenManagementReceipt = ReceiptManagementScreenP.getInstanceReceiptManagementScreenP();
			if(screenManagementReceipt.getParent() == null){
				desktopPane.add(screenManagementReceipt);
			}
			screenManagementReceipt.setVisible(true);
			desktopPane.moveToFront(screenManagementReceipt);
			try {
				screenManagementReceipt.setSelected(true);
			} catch (PropertyVetoException e1) {
				// TODO Auto-generated catch block
				e1.printStackTrace();
			}
			
		}  
	}
}