// Autogenerated by EvDSL
package riseevents.ev.table;
import riseevents.ev.util.LibraryOfDSL;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import riseevents.ev.util.ExceptionMessages;
import riseevents.ev.data.NewClass;

public class NewClassTableModel extends AbstractTableModel{
	// Nome das Colunas
		
			private static final int COL_NEWCLASSID = 0
			private static final int COL_AAAA = 1;
			private static final int COL_BBBB = 2;
			
			// Lista de Valores
			private List<NewClass> rows;
			
			public NewClassTableModel(List<NewClass> values){
				this.rows = values;
			}
			
			public int getRowCount() {
				return rows.size();
			}
			
			//Quantidade de Colunas
			public int getColumnCount() {
				return 2;
			}
			
			//Preenchimento de cada coluna
				public Object getValueAt(int rowIndex, int columnIndex) {
					NewClass newclass = rows.get(rowIndex);
					if (columnIndex == COL_NEWCLASSID) {
						return newclass.getIdNewClass();
					}
					else if (columnIndex == COL_AAAA) {
						return newclass.getAaaa();
					}  
					else if (columnIndex == COL_BBBB) {
						return newclass.getBbbb();
					}  
					return null;
				}
				
				@Override
				public String getColumnName(int column) {
					String coluna = "";
					switch (column) {
					
					default:
						throw new IllegalArgumentException(ExceptionMessages.EXC_INVALID_COL);
					}
					return coluna;
				}
				
				//Tipo de valor da colna
				@Override
				public Class<?> getColumnClass(int columnIndex) {
					return null;
				}
				
				//Abaixo metodos de InserÁ„o, remoÁ„o, update e etc;
				public NewClass get(int row) {
					return rows.get(row);
				}

				public void addNewClass(NewClass newclass) {
					rows.add(newclass);
					int ultimoIndice = getRowCount() - 1;
					fireTableRowsInserted(ultimoIndice, ultimoIndice);
				}
				
				public void removeNewClass(int indiceLinha) {
					rows.remove(indiceLinha);
					fireTableRowsDeleted(indiceLinha, indiceLinha);
				}
				
				public void alterarNewClass(int indiceLinha, NewClass newclass) {
					rows.get(indiceLinha).setAaaa(newclass.getAaaa());		
					rows.get(indiceLinha).setBbbb(newclass.getBbbb());		
					fireTableDataChanged();
				}
				
				//real name listade....
				public void addNewClassList(List<NewClass> newclassList) {
					int indice = getRowCount();
					rows.addAll(NewClassList);
					fireTableRowsInserted(indice, indice + NewClassList.size());
				}
				
				public int retornarIndice(NewClass newclass) {
					return rows.indexOf(newclass);
				}
				
				// Remove todos os registros.
				public void limpar() {
					rows.clear();

					// Notifica a mudança.
					fireTableDataChanged();
				}
}