// Autogenerated by EvDSL
package riseevents.ev.table;
import riseevents.ev.util.LibraryOfDSL;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import riseevents.ev.data.NewClass;

public class NewClassTableModel extends AbstractTableModel{
	// Nome das Colunas
	
			private static final int COL_ACTIVITYID = 0;
			private static final int COL_ORGANIZERID = 1;
			
			// Lista de Valores
			private List<NewClass> rows;
			
			public NewClassTableModel(List<newclass> values){
				this.rows = values;
			}
			
			public int getRowCount() {
				return rows.size();
			}
			
			//Quantidade de Colunas
			public int getColumnCount() {
				return 2;
			}
			
			//Preenchimento de cada coluna
				public Object getValueAt(int rowIndex, int columnIndex) {
					NewClass newclass = rows.get(rowIndex);
					if (columnIndex == COL_ACTIVITYID) {
						return newclass.getIdActivity();
					}  else if (columnIndex == COL_ORGANIZERID) {
						return newclass.getIdOrganizer();
					} 
					return null;
				}
				
				@Override
				public String getColumnName(int column) {
					String coluna = "";
					switch (column) {
					
					default:
						throw new IllegalArgumentException(EXC_INVALID_COL);
					}
					return coluna;
				}
				
				//Tipo de valor da colna
				@Override
				public Class<?> getColumnClass(int columnIndex) {
					return null;
				}
				
				//Abaixo metodos de InserÁ„o, remoÁ„o, update e etc;
				public NewClass get(int row) {
					return rows.get(row);
				}

				public void addNewClass(NewClass ) {
					rows.add();
					int ultimoIndice = getRowCount() - 1;
					fireTableRowsInserted(ultimoIndice, ultimoIndice);
				}
				
				public void removeNewClass(int indiceLinha) {
					rows.remove(indiceLinha);
					fireTableRowsDeleted(indiceLinha, indiceLinha);
				}
				
				public void alterarNewClass(int indiceLinha, NewClass newclass) {
					rows.get(indiceLinha).setBanana(newclass.getbanana());		
					fireTableDataChanged();
				}
				
				//real name listade....
				public void addNewClassList(List<NewClass> newclassList) {
					int indice = getRowCount();
					rows.addAll(NewClasss);
					fireTableRowsInserted(indice, indice + NewClasss.size());
				}
				
				public int retornarIndice(NewClass newclass) {
					return rows.indexOf(NewClass);
				}
				
				// Remove todos os registros.
				public void limpar() {
					rows.clear();

					// Notifica a mudança.
					fireTableDataChanged();
				}
}