// Autogenerated by EvDSL
package riseevents.ev.table;
import riseevents.ev.util.LibraryOfDSL;

import java.util.List;

import javax.swing.table.AbstractTableModel;

import riseevents.ev.util.ExceptionMessages;
import riseevents.ev.data.Newclass;

public class NewclassTableModel extends AbstractTableModel{
	// Nome das Colunas
		
			private static final int COL_NEWCLASSID = 0
			private static final int COL_AAAA = 1;
			private static final int COL_BBBB = 2;
			
			// Lista de Valores
			private List<Newclass> rows;
			
			public NewclassTableModel(List<Newclass> values){
				this.rows = values;
			}
			
			public int getRowCount() {
				return rows.size();
			}
			
			//Quantidade de Colunas
			public int getColumnCount() {
				return 2;
			}
			
			//Preenchimento de cada coluna
				public Object getValueAt(int rowIndex, int columnIndex) {
					Newclass newclass = rows.get(rowIndex);
					if (columnIndex == COL_NEWCLASSID) {
						return newclass.getIdNewclass();
					}
					else if (columnIndex == COL_AAAA) {
						return newclass.getAaaa();
					}  
					else if (columnIndex == COL_BBBB) {
						return newclass.getBbbb();
					}  
					return null;
				}
				
				@Override
				public String getColumnName(int column) {
					String coluna = "";
					switch (column) {
					
					default:
						throw new IllegalArgumentException(ExceptionMessages.EXC_INVALID_COL);
					}
					return coluna;
				}
				
				//Tipo de valor da colna
				@Override
				public Class<?> getColumnClass(int columnIndex) {
					return null;
				}
				
				//Abaixo metodos de InserÁ„o, remoÁ„o, update e etc;
				public Newclass get(int row) {
					return rows.get(row);
				}

				public void addNewclass(Newclass newclass) {
					rows.add(newclass);
					int ultimoIndice = getRowCount() - 1;
					fireTableRowsInserted(ultimoIndice, ultimoIndice);
				}
				
				public void removeNewclass(int indiceLinha) {
					rows.remove(indiceLinha);
					fireTableRowsDeleted(indiceLinha, indiceLinha);
				}
				
				public void alterarNewclass(int indiceLinha, Newclass newclass) {
					rows.get(indiceLinha).setAaaa(newclass.getAaaa());		
					rows.get(indiceLinha).setBbbb(newclass.getBbbb());		
					fireTableDataChanged();
				}
				
				//real name listade....
				public void addNewclassList(List<Newclass> newclassList) {
					int indice = getRowCount();
					rows.addAll(NewclassList);
					fireTableRowsInserted(indice, indice + NewclassList.size());
				}
				
				public int retornarIndice(Newclass newclass) {
					return rows.indexOf(newclass);
				}
				
				// Remove todos os registros.
				public void limpar() {
					rows.clear();

					// Notifica a mudança.
					fireTableDataChanged();
				}
}