//#if ${SubmissionParcial} == "T" or ${SubmissionCompleta} == "T"
package evco.ev.business;

import java.io.File;
import java.util.List;

import evco.ev.data.Submission;
import evco.ev.exception.RepositoryException;
import evco.ev.exception.SubmissionAlreadyInsertedException;
import evco.ev.exception.SubmissionNotFoundException;
import evco.ev.repository.SubmissionRepository;


public class SubmissionControl {
	
    private SubmissionRepository submissionList;
	
	public SubmissionControl(SubmissionRepository repository){
		this.submissionList = repository;
	}
	public void remove(int idSubmission) throws SubmissionAlreadyInsertedException, RepositoryException, SubmissionNotFoundException{
		submissionList.remove(idSubmission);
	}
	
	public List<Submission> getSubmissionList() throws RepositoryException {
		return submissionList.getSubmissionList();  
	}
	
	public int getSubmissionLastId() throws RepositoryException{
		return submissionList.getSubmissionLastId();
	}

	public int getSubmissionIdByTitle(String submissionTitle) throws RepositoryException{
		return submissionList.getSubmissionIdByTitle(submissionTitle);
	}

	public Submission search(int idSubmission) throws SubmissionAlreadyInsertedException, RepositoryException, SubmissionNotFoundException{
		return submissionList.search(idSubmission);
	}

	// Generated by DSL
	public void inserAttachmanet(File attachment, int idActivity) throws SubmissionAlreadyInsertedException, RepositoryException{
		submissionList.insert(attachment, idActivity);
	}
	//
	public void pdfRecover(int idSubmission) throws RepositoryException {
		submissionList.pdfRecover(idSubmission);
	}
	
	public List<Submission> getSubmissionsByUser(int idUser) throws RepositoryException{
		return submissionList.getSubmissionsByUser(idUser);
	}
}
//#endif