// Autogenerated by EvDSL
package riseevents.ev.repository;
import riseevents.ev.util.LibraryOfDSL;
import java.util.List;
import riseevents.ev.data.NewOption;
import riseevents.ev.exception.NewOptionNotFoundException;
import riseevents.ev.exception.RepositoryException;

public interface NewOptionRepository {

	public void insert(NewOption newoption) throws RepositoryException;

	public void remove(int idNewOption) throws NewOptionNotFoundException, RepositoryException;

	public NewOption search(int idEntity) throws NewOptionNotFoundException, RepositoryException;
	
	public List<NewOption> getNewOptionList() throws RepositoryException;

	public void update(NewOption newoption) throws NewOptionNotFoundException, RepositoryException;

	public boolean isThere(int idEntity) throws RepositoryException;
	
	public int getNewOptionLastId() throws RepositoryException;
	
	public List<NewOption> getEntityById(int idEntity) throws RepositoryException, NewOptionNotFoundException;

}