// Autogenerated by EvDSL
package riseevents.ev.exception;
import riseevents.ev.util.LibraryOfDSL;
import riseevents.ev.util.ExceptionMessages;

public class NewOptionAlreadyInsertedException extends Exception {

	private int idEntity;

	public NewOptionAlreadyInsertedException(int idEntity) {
		super(ExceptionMessages.EXC_ALREADY_EXISTS);
		this.idEntity = idEntity;
	}

	public int getIdNewOption() {
		return idEntity;
	}
}
//#endif