// Autogenerated by EvDSL
package riseevents.ev.exception;
import riseevents.ev.util.LibraryOfDSL;
import riseevents.ev.util.ExceptionMessages;

public class NewOptionNotFoundException extends Exception {
    private int idEntity;

    public NewOptionNotFoundException(int idEntity){
        super (ExceptionMessages.EXC_NOT_FOUND);
        this.idEntity = idEntity;
    }

    public int getIdNewOption(){
        return idEntity;
    }

}