// Autogenerated by EvDSL
package evco.ev.facade;
import evco.ev.util.LibraryOfDSL;

import java.io.File;
import java.io.IOException;
import java.util.List;
import java.util.Set;

import org.apache.commons.mail.EmailException;
import evco.ev.data.User;
import evco.ev.business.UserControl;
import evco.ev.exception.UserAlreadyInsertedException;
import evco.ev.exception.UserNotFoundException;
import evco.ev.repository.UserRepository;
import evco.ev.repository.UserRepositoryBDR;
import evco.ev.data.Reviewer;
import evco.ev.business.ReviewerControl;
import evco.ev.exception.ReviewerAlreadyInsertedException;
import evco.ev.exception.ReviewerNotFoundException;
import evco.ev.repository.ReviewerRepository;
import evco.ev.repository.ReviewerRepositoryBDR;
import evco.ev.data.Speaker;
import evco.ev.business.SpeakerControl;
import evco.ev.exception.SpeakerAlreadyInsertedException;
import evco.ev.exception.SpeakerNotFoundException;
import evco.ev.repository.SpeakerRepository;
import evco.ev.repository.SpeakerRepositoryBDR;
import evco.ev.data.Event;
import evco.ev.business.EventControl;
import evco.ev.exception.EventAlreadyInsertedException;
import evco.ev.exception.EventNotFoundException;
import evco.ev.repository.EventRepository;
import evco.ev.repository.EventRepositoryBDR;
import evco.ev.data.Payment;
import evco.ev.business.PaymentControl;
import evco.ev.exception.PaymentAlreadyInsertedException;
import evco.ev.exception.PaymentNotFoundException;
import evco.ev.repository.PaymentRepository;
import evco.ev.repository.PaymentRepositoryBDR;
import evco.ev.data.Activity;
import evco.ev.business.ActivityControl;
import evco.ev.exception.ActivityAlreadyInsertedException;
import evco.ev.exception.ActivityNotFoundException;
import evco.ev.repository.ActivityRepository;
import evco.ev.repository.ActivityRepositoryBDR;
import evco.ev.data.Submission;
import evco.ev.business.SubmissionControl;
import evco.ev.exception.SubmissionAlreadyInsertedException;
import evco.ev.exception.SubmissionNotFoundException;
import evco.ev.repository.SubmissionRepository;
import evco.ev.repository.SubmissionRepositoryBDR;
import evco.ev.data.Author;
import evco.ev.business.AuthorControl;
import evco.ev.exception.AuthorAlreadyInsertedException;
import evco.ev.exception.AuthorNotFoundException;
import evco.ev.repository.AuthorRepository;
import evco.ev.repository.AuthorRepositoryBDR;
import evco.ev.data.CheckingCopy;
import evco.ev.business.CheckingCopyControl;
import evco.ev.exception.CheckingCopyAlreadyInsertedException;
import evco.ev.exception.CheckingCopyNotFoundException;
import evco.ev.repository.CheckingCopyRepository;
import evco.ev.repository.CheckingCopyRepositoryBDR;
import evco.ev.exception.RepositoryException;
import com.lowagie.text.DocumentException;

import evco.ev.data.Review;
import evco.ev.business.ReviewControl;
import evco.ev.exception.ReviewAlreadyInsertedException;
import evco.ev.exception.ReviewNotFoundException;
import evco.ev.repository.ReviewRepository;
import evco.ev.repository.ReviewRepositoryBDR;
import evco.ev.data.ActivityUser;
import evco.ev.business.ActivityUserControl;
import evco.ev.exception.ActivityUserAlreadyInsertedException;
import evco.ev.exception.ActivityUserNotFoundException;
import evco.ev.repository.ActivityUserRepository;
import evco.ev.repository.ActivityUserRepositoryBDR;
import evco.ev.data.ActivitySpeaker;
import evco.ev.business.ActivitySpeakerControl;
import evco.ev.exception.ActivitySpeakerAlreadyInsertedException;
import evco.ev.exception.ActivitySpeakerNotFoundException;
import evco.ev.repository.ActivitySpeakerRepository;
import evco.ev.repository.ActivitySpeakerRepositoryBDR;
import evco.ev.data.SubmissionAuthor;
import evco.ev.business.SubmissionAuthorControl;
import evco.ev.exception.SubmissionAuthorAlreadyInsertedException;
import evco.ev.exception.SubmissionAuthorNotFoundException;
import evco.ev.repository.SubmissionAuthorRepository;
import evco.ev.repository.SubmissionAuthorRepositoryBDR;
import evco.ev.data.SubmissionUser;
import evco.ev.business.SubmissionUserControl;
import evco.ev.exception.SubmissionUserAlreadyInsertedException;
import evco.ev.exception.SubmissionUserNotFoundException;
import evco.ev.repository.SubmissionUserRepository;
import evco.ev.repository.SubmissionUserRepositoryBDR;
import evco.ev.data.Registration;
import evco.ev.business.RegistrationControl;
import evco.ev.exception.RegistrationAlreadyInsertedException;
import evco.ev.exception.RegistrationNotFoundException;
import evco.ev.repository.RegistrationRepository;
import evco.ev.repository.RegistrationRepositoryBDR;
import evco.ev.data.Assignment;
import evco.ev.business.AssignmentControl;
import evco.ev.exception.AssignmentAlreadyInsertedException;
import evco.ev.exception.AssignmentNotFoundException;
import evco.ev.repository.AssignmentRepository;
import evco.ev.repository.AssignmentRepositoryBDR;

public class EvCoFacade {

	private UserControl userList;
	private ReviewerControl reviewerList;
	private SpeakerControl speakerList;
	private EventControl eventList;
	private PaymentControl paymentList;
	private ActivityControl activityList;
	private SubmissionControl submissionList;
	private AuthorControl authorList;
	private CheckingCopyControl checkingcopyList;
	private ReviewControl reviewList;
	private ActivityUserControl activityuserList;
	private ActivitySpeakerControl activityspeakerList;
	private SubmissionAuthorControl submissionauthorList;
	private SubmissionUserControl submissionuserList;
	private RegistrationControl registrationList;
	private AssignmentControl assignmentList;

	protected static EvCoFacade instance;
	
	public EvCoFacade(){
		UserRepository userRepository = UserRepositoryBDR.getInstance();
		ReviewerRepository reviewerRepository = ReviewerRepositoryBDR.getInstance();
		SpeakerRepository speakerRepository = SpeakerRepositoryBDR.getInstance();
		EventRepository eventRepository = EventRepositoryBDR.getInstance();
		PaymentRepository paymentRepository = PaymentRepositoryBDR.getInstance();
		ActivityRepository activityRepository = ActivityRepositoryBDR.getInstance();
		SubmissionRepository submissionRepository = SubmissionRepositoryBDR.getInstance();
		AuthorRepository authorRepository = AuthorRepositoryBDR.getInstance();
		CheckingCopyRepository checkingcopyRepository = CheckingCopyRepositoryBDR.getInstance();
		
		userList = new UserControl(userRepository); 
		reviewerList = new ReviewerControl(reviewerRepository); 
		speakerList = new SpeakerControl(speakerRepository); 
		eventList = new EventControl(eventRepository); 
		paymentList = new PaymentControl(paymentRepository); 
		activityList = new ActivityControl(activityRepository); 
		submissionList = new SubmissionControl(submissionRepository); 
		authorList = new AuthorControl(authorRepository); 
		checkingcopyList = new CheckingCopyControl(checkingcopyRepository); 
	
	
		ReviewRepository reviewRepository = ReviewRepositoryBDR.getInstance();
		ActivityUserRepository activityuserRepository = ActivityUserRepositoryBDR.getInstance();
		ActivitySpeakerRepository activityspeakerRepository = ActivitySpeakerRepositoryBDR.getInstance();
		SubmissionAuthorRepository submissionauthorRepository = SubmissionAuthorRepositoryBDR.getInstance();
		SubmissionUserRepository submissionuserRepository = SubmissionUserRepositoryBDR.getInstance();
		RegistrationRepository registrationRepository = RegistrationRepositoryBDR.getInstance();
		AssignmentRepository assignmentRepository = AssignmentRepositoryBDR.getInstance();
		
		reviewList = new ReviewControl(reviewRepository); 
		activityuserList = new ActivityUserControl(activityuserRepository); 
		activityspeakerList = new ActivitySpeakerControl(activityspeakerRepository); 
		submissionauthorList = new SubmissionAuthorControl(submissionauthorRepository); 
		submissionuserList = new SubmissionUserControl(submissionuserRepository); 
		registrationList = new RegistrationControl(registrationRepository); 
		assignmentList = new AssignmentControl(assignmentRepository); 
	
	}
	
	public static EvCoFacade getInstance()  {
		if (EvCoFacade.instance == null) {
			EvCoFacade.instance = new EvCoFacade();
		}
		return EvCoFacade.instance;
	}
	
	public void insertUser(User entity) throws UserAlreadyInsertedException, RepositoryException{
		this.userList.insert(entity);
	}
	public void removeUser(int idEntity) throws UserNotFoundException, RepositoryException, UserAlreadyInsertedException{
		userList.remove(idEntity);  
	}
	public void updateUser(User Entity) throws UserNotFoundException, RepositoryException, UserAlreadyInsertedException{
		userList.update(Entity);
	}
	public List<User> getUserList() throws RepositoryException{
		return userList.getUserList();
	}
	public User searchUser(int idEntity) throws UserNotFoundException, RepositoryException, UserAlreadyInsertedException{
		return userList.search(idEntity);
	}
	public boolean isThereUser(int idEntity) throws RepositoryException{
		return userList.isThere(idEntity);
	}
	public void insertReviewer(Reviewer entity) throws ReviewerAlreadyInsertedException, RepositoryException{
		this.reviewerList.insert(entity);
	}
	public void removeReviewer(int idEntity) throws ReviewerNotFoundException, RepositoryException, ReviewerAlreadyInsertedException{
		reviewerList.remove(idEntity);  
	}
	public void updateReviewer(Reviewer Entity) throws ReviewerNotFoundException, RepositoryException, ReviewerAlreadyInsertedException{
		reviewerList.update(Entity);
	}
	public List<Reviewer> getReviewerList() throws RepositoryException{
		return reviewerList.getReviewerList();
	}
	public Reviewer searchReviewer(int idEntity) throws ReviewerNotFoundException, RepositoryException, ReviewerAlreadyInsertedException{
		return reviewerList.search(idEntity);
	}
	public boolean isThereReviewer(int idEntity) throws RepositoryException{
		return reviewerList.isThere(idEntity);
	}
	public void insertSpeaker(Speaker entity) throws SpeakerAlreadyInsertedException, RepositoryException{
		this.speakerList.insert(entity);
	}
	public void removeSpeaker(int idEntity) throws SpeakerNotFoundException, RepositoryException, SpeakerAlreadyInsertedException{
		speakerList.remove(idEntity);  
	}
	public void updateSpeaker(Speaker Entity) throws SpeakerNotFoundException, RepositoryException, SpeakerAlreadyInsertedException{
		speakerList.update(Entity);
	}
	public List<Speaker> getSpeakerList() throws RepositoryException{
		return speakerList.getSpeakerList();
	}
	public Speaker searchSpeaker(int idEntity) throws SpeakerNotFoundException, RepositoryException, SpeakerAlreadyInsertedException{
		return speakerList.search(idEntity);
	}
	public boolean isThereSpeaker(int idEntity) throws RepositoryException{
		return speakerList.isThere(idEntity);
	}
	public void insertEvent(Event entity) throws EventAlreadyInsertedException, RepositoryException{
		this.eventList.insert(entity);
	}
	public void removeEvent(int idEntity) throws EventNotFoundException, RepositoryException, EventAlreadyInsertedException{
		eventList.remove(idEntity);  
	}
	public void updateEvent(Event Entity) throws EventNotFoundException, RepositoryException, EventAlreadyInsertedException{
		eventList.update(Entity);
	}
	public List<Event> getEventList() throws RepositoryException{
		return eventList.getEventList();
	}
	public Event searchEvent(int idEntity) throws EventNotFoundException, RepositoryException, EventAlreadyInsertedException{
		return eventList.search(idEntity);
	}
	public int getEventLastId() throws RepositoryException{
		return eventList.getEventLastId();
	}
	public boolean isThereEvent(int idEntity) throws RepositoryException{
		return eventList.isThere(idEntity);
	}
	public void insertPayment(Payment entity) throws PaymentAlreadyInsertedException, RepositoryException{
		this.paymentList.insert(entity);
	}
	public void removePayment(int idEntity) throws PaymentNotFoundException, RepositoryException, PaymentAlreadyInsertedException{
		paymentList.remove(idEntity);  
	}
	public void updatePayment(Payment Entity) throws PaymentNotFoundException, RepositoryException, PaymentAlreadyInsertedException{
		paymentList.update(Entity);
	}
	public List<Payment> getPaymentList() throws RepositoryException{
		return paymentList.getPaymentList();
	}
	public Payment searchPayment(int idEntity) throws PaymentNotFoundException, RepositoryException, PaymentAlreadyInsertedException{
		return paymentList.search(idEntity);
	}
	public int getPaymentLastId() throws RepositoryException{
		return paymentList.getPaymentLastId();
	}
	public void insertActivity(Activity entity) throws ActivityAlreadyInsertedException, RepositoryException{
		this.activityList.insert(entity);
	}
	public void removeActivity(int idEntity) throws ActivityNotFoundException, RepositoryException, ActivityAlreadyInsertedException{
		activityList.remove(idEntity);  
	}
	public void updateActivity(Activity Entity) throws ActivityNotFoundException, RepositoryException, ActivityAlreadyInsertedException{
		activityList.update(Entity);
	}
	public List<Activity> getActivityList() throws RepositoryException{
		return activityList.getActivityList();
	}
	public Activity searchActivity(int idEntity) throws ActivityNotFoundException, RepositoryException, ActivityAlreadyInsertedException{
		return activityList.search(idEntity);
	}
	public int getActivityLastId() throws RepositoryException{
		return activityList.getActivityLastId();
	}
	public boolean isThereActivity(int idEntity) throws RepositoryException{
		return activityList.isThere(idEntity);
	}
	public void removeSubmission(int idEntity) throws SubmissionNotFoundException, RepositoryException, SubmissionAlreadyInsertedException{
		submissionList.remove(idEntity);  
	}
	public List<Submission> getSubmissionList() throws RepositoryException{
		return submissionList.getSubmissionList();
	}
	public Submission searchSubmission(int idEntity) throws SubmissionNotFoundException, RepositoryException, SubmissionAlreadyInsertedException{
		return submissionList.search(idEntity);
	}
	public int getSubmissionLastId() throws RepositoryException{
		return submissionList.getSubmissionLastId();
	}
	public List<Author> getAuthorList() throws RepositoryException{
		return authorList.getAuthorList();
	}
	public int getAuthorLastId() throws RepositoryException{
		return authorList.getAuthorLastId();
	}
	public boolean isThereAuthor(int idEntity) throws RepositoryException{
		return authorList.isThere(idEntity);
	}
	public void insertCheckingCopy(CheckingCopy entity) throws CheckingCopyAlreadyInsertedException, RepositoryException{
		this.checkingcopyList.insert(entity);
	}
	public void removeCheckingCopy(int idEntity) throws CheckingCopyNotFoundException, RepositoryException, CheckingCopyAlreadyInsertedException{
		checkingcopyList.remove(idEntity);  
	}
	public void updateCheckingCopy(CheckingCopy Entity) throws CheckingCopyNotFoundException, RepositoryException, CheckingCopyAlreadyInsertedException{
		checkingcopyList.update(Entity);
	}
	public List<CheckingCopy> getCheckingCopyList() throws RepositoryException{
		return checkingcopyList.getCheckingCopyList();
	}
	public CheckingCopy searchCheckingCopy(int idEntity) throws CheckingCopyNotFoundException, RepositoryException, CheckingCopyAlreadyInsertedException{
		return checkingcopyList.search(idEntity);
	}
	public int getCheckingCopyLastId() throws RepositoryException{
		return checkingcopyList.getCheckingCopyLastId();
	}
	public void insertReview(Review entity) throws ReviewAlreadyInsertedException, RepositoryException{
		this.reviewList.insert(entity);
	}
	public void updateReview(Review Entity) throws ReviewNotFoundException, RepositoryException, ReviewAlreadyInsertedException{
		reviewList.update(Entity);
	}
	public List<Review> getReviewList() throws RepositoryException{
		return reviewList.getReviewList();
	}
	public int getReviewLastId() throws RepositoryException{
		return reviewList.getReviewLastId();
	}
	public void insertActivityUser(ActivityUser entity) throws ActivityUserAlreadyInsertedException, RepositoryException{
		this.activityuserList.insert(entity);
	}
	public void removeActivityUser(ActivityUser entity) throws ActivityUserNotFoundException, RepositoryException, ActivityUserAlreadyInsertedException{
		activityuserList.remove(entity);  
	}
	public void updateActivityUser(ActivityUser Entity) throws ActivityUserNotFoundException, RepositoryException, ActivityUserAlreadyInsertedException{
		activityuserList.update(Entity);
	}
	public List<ActivityUser> getActivityUserList() throws RepositoryException{
		return activityuserList.getActivityUserList();
	}
	public int getActivityUserLastId() throws RepositoryException{
		return activityuserList.getActivityUserLastId();
	}
	public boolean isThereActivityUser(ActivityUser entity) throws RepositoryException{
		return activityuserList.isThere(entity);
	}
	public void insertActivitySpeaker(ActivitySpeaker entity) throws ActivitySpeakerAlreadyInsertedException, RepositoryException{
		this.activityspeakerList.insert(entity);
	}
	public void removeActivitySpeaker(ActivitySpeaker entity) throws ActivitySpeakerNotFoundException, RepositoryException, ActivitySpeakerAlreadyInsertedException{
		activityspeakerList.remove(entity);  
	}
	public void updateActivitySpeaker(ActivitySpeaker Entity) throws ActivitySpeakerNotFoundException, RepositoryException, ActivitySpeakerAlreadyInsertedException{
		activityspeakerList.update(Entity);
	}
	public List<ActivitySpeaker> getActivitySpeakerList() throws RepositoryException{
		return activityspeakerList.getActivitySpeakerList();
	}
	public ActivitySpeaker searchActivitySpeaker(ActivitySpeaker Entity) throws ActivitySpeakerNotFoundException, RepositoryException, ActivitySpeakerAlreadyInsertedException{
		return activityspeakerList.search(Entity);
	}
	public int getActivitySpeakerLastId() throws RepositoryException{
		return activityspeakerList.getActivitySpeakerLastId();
	}
	public boolean isThereActivitySpeaker(ActivitySpeaker entity) throws RepositoryException{
		return activityspeakerList.isThere(entity);
	}
	public void insertSubmissionAuthor(SubmissionAuthor entity) throws SubmissionAuthorAlreadyInsertedException, RepositoryException{
		this.submissionauthorList.insert(entity);
	}
	public void removeSubmissionAuthor(SubmissionAuthor entity) throws SubmissionAuthorNotFoundException, RepositoryException, SubmissionAuthorAlreadyInsertedException{
		submissionauthorList.remove(entity);  
	}
	public void updateSubmissionAuthor(SubmissionAuthor Entity) throws SubmissionAuthorNotFoundException, RepositoryException, SubmissionAuthorAlreadyInsertedException{
		submissionauthorList.update(Entity);
	}
	public List<SubmissionAuthor> getSubmissionAuthorList() throws RepositoryException{
		return submissionauthorList.getSubmissionAuthorList();
	}
	public SubmissionAuthor searchSubmissionAuthor(SubmissionAuthor Entity) throws SubmissionAuthorNotFoundException, RepositoryException, SubmissionAuthorAlreadyInsertedException{
		return submissionauthorList.search(Entity);
	}
	public boolean isThereSubmissionAuthor(SubmissionAuthor entity) throws RepositoryException{
		return submissionauthorList.isThere(entity);
	}
	public void insertSubmissionUser(SubmissionUser entity) throws SubmissionUserAlreadyInsertedException, RepositoryException{
		this.submissionuserList.insert(entity);
	}
	public void removeSubmissionUser(SubmissionUser entity) throws SubmissionUserNotFoundException, RepositoryException, SubmissionUserAlreadyInsertedException{
		submissionuserList.remove(entity);  
	}
	public void updateSubmissionUser(SubmissionUser Entity) throws SubmissionUserNotFoundException, RepositoryException, SubmissionUserAlreadyInsertedException{
		submissionuserList.update(Entity);
	}
	public List<SubmissionUser> getSubmissionUserList() throws RepositoryException{
		return submissionuserList.getSubmissionUserList();
	}
	public SubmissionUser searchSubmissionUser(SubmissionUser Entity) throws SubmissionUserNotFoundException, RepositoryException, SubmissionUserAlreadyInsertedException{
		return submissionuserList.search(Entity);
	}
	public boolean isThereSubmissionUser(SubmissionUser entity) throws RepositoryException{
		return submissionuserList.isThere(entity);
	}
	public void insertRegistration(Registration entity) throws RegistrationAlreadyInsertedException, RepositoryException{
		this.registrationList.insert(entity);
	}
	public void updateRegistration(Registration Entity) throws RegistrationNotFoundException, RepositoryException, RegistrationAlreadyInsertedException{
		registrationList.update(Entity);
	}
	public List<Registration> getRegistrationList() throws RepositoryException{
		return registrationList.getRegistrationList();
	}
	public int getRegistrationLastId() throws RepositoryException{
		return registrationList.getRegistrationLastId();
	}
	public boolean isThereRegistration(Registration entity) throws RepositoryException{
		return registrationList.isThere(entity);
	}
	public void insertAssignment(Assignment entity) throws AssignmentAlreadyInsertedException, RepositoryException{
		this.assignmentList.insert(entity);
	}
	public void removeAssignment(Assignment entity) throws AssignmentNotFoundException, RepositoryException, AssignmentAlreadyInsertedException{
		assignmentList.remove(entity);  
	}
	public void updateAssignment(Assignment Entity) throws AssignmentNotFoundException, RepositoryException, AssignmentAlreadyInsertedException{
		assignmentList.update(Entity);
	}
	public List<Assignment> getAssignmentList() throws RepositoryException{
		return assignmentList.getAssignmentList();
	}
	public Assignment searchAssignment(Assignment Entity) throws AssignmentNotFoundException, RepositoryException, AssignmentAlreadyInsertedException{
		return assignmentList.search(Entity);
	}
	public boolean isThereAssignment(Assignment entity) throws RepositoryException{
		return assignmentList.isThere(entity);
	}
	public List<ActivitySpeaker> getActivitiesSpeakerById(int idActivity) throws RepositoryException{
		return activityspeakerList.getActivitiesById(idActivity);
	}
	public List<ActivityUser> getActivitiesUsersById(int idActivity) throws RepositoryException{
		return activityuserList.getActivitiesById(idActivity);
	}
 	public List<Activity> getActivitiesByEvent(int idEvent) throws RepositoryException{
		return activityList.getActivitiesByEvent(idEvent);
	}
	
	public int getEventIdByName(String entityName) throws RepositoryException{
		return eventList.getEventIdByName(entityName);
	}
	
	public int getUserIdByName(String entityName) throws RepositoryException{
		return userList.getUserIdByName(entityName);
	}

	
	
	public int getActivityIdByName(String entityName) throws RepositoryException{
		return activityList.getActivityIdByName(entityName);
	}

	public float getEventMainTrackValue(int idEvent) throws RepositoryException{
		return activityList.getEventMainTrackValue(idEvent);
	}
	
	public int getActivityMainTrackId(int idEvent) throws RepositoryException{
		return activityList.getActivityMainTrackId(idEvent);
	}
	
	public int getEventbyActivity(int idActivity) throws RepositoryException{
		return activityList.getEventbyActivity(idActivity);
	}
	

	
public Author searchAuthor(int idAuthor) throws AuthorNotFoundException, RepositoryException, AuthorAlreadyInsertedException{
	return authorList.search(idAuthor);
} 
	
	
	public void removeValue(float value, int idRegistration) throws RepositoryException{
		registrationList.removeValue(value, idRegistration);
	}
	public void addValue(float value, int idRegistration) throws RepositoryException{
		registrationList.addValue(value, idRegistration);
	}
	public void removeRegistration(int idRegistration) throws RegistrationNotFoundException, RepositoryException, RegistrationAlreadyInsertedException{
		registrationList.remove(idRegistration);  
	}
	public int searchRegistration(int idUser, int idEvent) throws RegistrationNotFoundException, RepositoryException{
		return registrationList.search(idUser, idEvent);
	}
	public Registration searchRegistration(int idRegistration) throws RegistrationNotFoundException, RepositoryException, RegistrationAlreadyInsertedException{
		return registrationList.search(idRegistration);
	}
	
	public void typePayment(Payment payment, Payment paymentout) throws DocumentException, IOException {
		this.paymentList.type(payment, paymentout);
	}
	
	
	public void pdfRecovey(int idSubmission) throws RepositoryException{
		this.submissionList.pdfRecover(idSubmission);
	}
	public List<Submission> getSubmissionsByUser(int idUser) throws RepositoryException{
		return submissionList.getSubmissionsByUser(idUser);
	}
	public int getSubmissionIdByTitle(String submissionTitle) throws RepositoryException{
		return submissionList.getSubmissionIdByTitle(submissionTitle);
	}
	
	public void removeReview(int idReview) throws ReviewNotFoundException, RepositoryException, ReviewAlreadyInsertedException{
		reviewList.remove(idReview);  
	}
	public Review searchReview(int idReview) throws ReviewNotFoundException, RepositoryException, ReviewAlreadyInsertedException{
		return reviewList.search(idReview);
	}
			
	public List<String> getReviewsBySubmission(int idSubmission) throws RepositoryException{
		return reviewList.getReviewsBySubmission(idSubmission);
	}

	public Reviewer getReviewerByknowledgeArea(String knowledgearea) throws ReviewerNotFoundException, RepositoryException, ReviewerAlreadyInsertedException{
		return reviewerList.getReviewerByknowledgeArea(knowledgearea);
	}
	
	public void generateProgram (List<Activity> activities, Event event) throws DocumentException, IOException{
		eventList.generateProgram(activities, event);
	}
	
	public void generateImportantDates(String abstractDate, String fullPaperDate, String notificationDate, Event event) throws DocumentException, IOException{
		eventList.generateImportantDates(abstractDate, fullPaperDate, notificationDate, event);
	}
	public List<String> getParticipantsPerEvent(int idEvent) throws RepositoryException{
		return eventList.getParticipantsPerEvent(idEvent);
	}
	public void frequencyPerEvent(List<String> ParticipantsPerEvent, Event event) throws DocumentException, IOException{
		eventList.frequencyPerEvent(ParticipantsPerEvent, event);
	}
	
}