//#if ${AssignmentChairindication} == "T" or ${Assignmentautomatic} == "T"
package {{systemName|lower}}.ev.business;

import java.util.List;

import org.apache.commons.mail.EmailException;


import {{systemName|lower}}.ev.data.Assignment;


import {{systemName|lower}}.ev.data.Review;
import {{systemName|lower}}.ev.data.User;
import {{systemName|lower}}.ev.exception.AssignmentAlreadyInsertedException;
import {{systemName|lower}}.ev.exception.AssignmentNotFoundException;
import {{systemName|lower}}.ev.exception.RepositoryException;
import {{systemName|lower}}.ev.repository.AssignmentRepository;
import {{systemName|lower}}.ev.util.Email;

public class AssignmentControl {
	
    private AssignmentRepository assignments;
	
	public AssignmentControl(AssignmentRepository repository){
		this.assignments = repository;
	}
	
	public void insert(Assignment assignment) throws AssignmentAlreadyInsertedException, RepositoryException{
		if (assignment != null) {
            if (!assignments.isThere(assignment)) {
                assignments.insert(assignment);
            } else {
                throw new AssignmentAlreadyInsertedException(assignment.getIdReview());
            }
        } else {
            throw new IllegalArgumentException();
        }
	}

	public void remove(Assignment assignment) throws AssignmentAlreadyInsertedException, RepositoryException, AssignmentNotFoundException{
		assignments.remove(assignment);
	}
	
	public void update(Assignment assignment) throws AssignmentAlreadyInsertedException, RepositoryException, AssignmentNotFoundException{
		assignments.update(assignment);
	}
	
	public Assignment search(Assignment assignment) throws AssignmentAlreadyInsertedException, RepositoryException, AssignmentNotFoundException{
		return assignments.search(assignment);
	}

	public boolean isThere(Assignment assignment) throws RepositoryException {
		return assignments.isThere(assignment);
	}

	public List<Assignment> getAssignments() throws RepositoryException {
		return assignments.getAssignments();  
	}
	
	{% if 'notificationsDeadline' in data.statments or 'notificationsPaperAssignemnt' in data.statments %}
	// Generated by DSL
	public void emailNotification(User user, Review review, Email email) throws EmailException{
		email.sendNotification(user, review);
	}
	//
	{% endif %}
}
//#endif