
package {{systemName|lower}}.ev.business;

import java.util.List;

import org.apache.commons.mail.EmailException;

import {{systemName|lower}}.ev.data.User;
import {{systemName|lower}}.ev.exception.RepositoryException;
import {{systemName|lower}}.ev.exception.UserAlreadyInsertedException;
import {{systemName|lower}}.ev.exception.UserNotFoundException;
//#if ${Organizer} == "T"
import {{systemName|lower}}.ev.repository.OrganizerRepository;
//#endif
//#if ${Reviewer} == "T"
import {{systemName|lower}}.ev.repository.ReviewerRepository;
//#endif
//#if ${Speaker} == "T"
import {{systemName|lower}}.ev.repository.SpeakerRepository;
//#endif
import {{systemName|lower}}.ev.repository.UserRepository;
import {{systemName|lower}}.ev.util.Email;

public class UserControl {

	private UserRepository users;
	//#if ${Speaker} == "T"
	private SpeakerRepository speakers;
	//#endif
	//#if ${Organizer} == "T"
	private OrganizerRepository organizers;
	//#endif
	//#if ${Reviewer} == "T"
	private ReviewerRepository reviewers;
	//#endif
	
	public UserControl(UserRepository repository){
		this.users = repository;
	}

	//usar instance of para saber qual o objeto dependendo disso direciona para o respectivo repositorio.
	{% if 'Insert' in data.commands %}
	public void insert(User user) throws UserAlreadyInsertedException, RepositoryException{
		if (user != null) {
			if (!users.isThere(user.getIdUser())) 
				users.insert(user);
			else
				throw new UserAlreadyInsertedException(user.getIdUser());
		} else {
            throw new IllegalArgumentException();
        }
	}
	{% endif %}
	{% if 'Remove' in data.commands %}
	public void remove(int idUser) throws UserAlreadyInsertedException, RepositoryException, UserNotFoundException{
		if (users.isThere(idUser)) 
			users.remove(idUser);
		else
			throw new UserNotFoundException(idUser);
	}
	{% endif %}
	{% if 'Update' in data.commands %}
	public void update(User user) throws UserAlreadyInsertedException, RepositoryException, UserNotFoundException{
		if (users.isThere(user.getIdUser())) 
			users.update(user);
		else
			throw new UserNotFoundException(user.getIdUser());
	}
	{% endif %}
	{% if 'Search' in data.commands %}
	public User search(int idUser) throws UserAlreadyInsertedException, RepositoryException, UserNotFoundException{
		return users.search(idUser);
	}
	{% endif %}

	public boolean isThere(int idUser) throws RepositoryException {
		return users.isThere(idUser);
	}
	
	public List<User> getUsers() throws RepositoryException { 
		return users.getUsers();  
	}
	
	public int getUserIdByName(String userName) throws RepositoryException{
		return users.getUserIdByName(userName);
	}

	{% if 'sendBugTrackEmail' in data.statments %}
	// Generated by DSL
	public String sendBug(String nome, String assunto, String mensagem, Email email) throws EmailException{
		return email.sendBugtrackEmail(nome, assunto, mensagem);
	}
	//
	{% endif %}
}
